open-power-sdk/pveclib

src/testsuite/arith128_test_i128.c, src/testsuite/arith128_test_i128.h, src/testsuite/pveclib_test.c
As this only effects older GCC vertions (GCC 7 and later are OK),
and there are simple work arounds, the GCC maintainers do not think it
is worth fixing.
For now we should just split arith128_test_i128.c (test_4b) into two
smaller functions: test_4b and test_4b1. This requires updates to
arith128_test_i128.h (extern for test_4b1) and pveclib_test.c
(add call to test_4b1).
This avoids the ICE for GCC5 (AT9.0) and GCC6 (AT10.0).
* src/testsuite/arith128_test_i128.c (test_4b): Split function
into two smaller functions named test_4b and test_4b1.
* src/testsuite/arith128_test_i128.h: Add test_4b1 extern.
* src/testsuite/pveclib_test.c (main): Add call to test_4b1.
=> For GCC 5/6 compiling arith128_test_i128.c (test_4b) with -g causes an ICE

src/testsuite/arith128_test_i128.c
* src/testsuite/arith128_test_i128.c (test_4b): Remove debug
only conditionals. Remove trailing blank line.
* src/testsuite/arith128_test_i128.c (test_4b1): Remove debug
only conditionals.
=> Cleanup white space and some left over debug only conditionals.

src/testsuite/arith128_test_i128.c, src/testsuite/arith128_test_i128.h, src/testsuite/pveclib_test.c, src/testsuite/vec_int128_dummy.c, src/vec_int128_ppc.h
The set of patches to fix the implementation of vec_srqi and vec_slqi and add the missing test cases, Also add the missing call to test_44 which test the reverse byte vector intrinsics
Fixes #7
=> Fix slqi srqi revb feb18

doc/pveclib-doxygen-pveclib.doxy, doc/pveclibmaindox.h, src/testsuite/arith128_print.c, src/testsuite/arith128_test_i128.c, src/testsuite/vec_int128_dummy.c, src/vec_bcd_ppc.h, src/vec_common_ppc.h, src/vec_int128_ppc.h
Fix the doxygen docs: Add a complete introduction; laying out the
rationale, issues, and plans. Reduce the noise from make doxygen-doc
by adding doxygen \brief comment for every function, typedef, and
macro. Correct the doxygen function descriptions so text and parms
have the same alignment. To make the examples clearer, simplify the
code by replacing some long in-line assembler sequences with equivalent
built-in functions from altivec.h.
On branch Fix_doxygen_Feb18
Changes to be committed:
modified:   doc/pveclib-doxygen-pveclib.doxy
modified:   doc/pveclibmaindox.h
modified:   src/testsuite/arith128_print.c
modified:   src/testsuite/arith128_test_i128.c
modified:   src/testsuite/vec_int128_dummy.c
modified:   src/vec_bcd_ppc.h
modified:   src/vec_common_ppc.h
modified: …
=> Fix the doxygen docs: Add a complete introduction; laying out the

src/vec_common_ppc.h, src/vec_f32_ppc.h, src/vec_f64_ppc.h, src/vec_int16_ppc.h, src/vec_int32_ppc.h, src/vec_int64_ppc.h
dependant changed to vec_common_ppc.h, and more fixes. These will not
be activated until parts change Makefile.am.
2018-05-27 Steven Munroe <munroesj52@gmail.com>
* src/vec_int16_ppc.h: New File.
* src/vec_int32_ppc.h: New File.
* src/vec_int64_ppc.h: New File.
* src/vec_common_ppc.h (CONST_VINT128_H, CONST_VINT16_H,
VEC_BYTE_L_DWH, VEC_BYTE_L_DWL): new Macro.
* src/vec_f64_ppc.h: Minor fixup.
=> First chunk of the power9 integer enablement. Starting with new files,

src/testsuite/arith128_test_bcd.c, src/testsuite/arith128_test_bcd.h, src/testsuite/arith128_test_char.c, src/testsuite/arith128_test_char.h, src/testsuite/arith128_test_i16.c, src/testsuite/arith128_test_i16.h, src/testsuite/arith128_test_i32.c, src/testsuite/arith128_test_i32.h, src/testsuite/arith128_test_i64.c, src/testsuite/arith128_test_i64.h
Some of these tests have been where in arith128_test_i128.c and moved
to the file with matching element size. Some test functions where given
more descriptive as part of this.
2018-06-11 Steven Munroe <munroesj52@gmail.com>
* src/testsuite/arith128_test_bcd.c: New File.
* src/testsuite/arith128_test_bcd.h: New File.
* src/testsuite/arith128_test_char.c: New File.
* src/testsuite/arith128_test_char.h: New file.
* src/testsuite/arith128_test_i16.c: Mew File.
* src/testsuite/arith128_test_i16.h: New File.
* src/testsuite/arith128_test_i32.c: New File.
* src/testsuite/arith128_test_i32.h: New File.
* src/testsuite/arith128_test_i64.c: New File.
* src/testsuite/arith128_test_i64.h: new File.
=> Refactor the unit tests by type and element size. Here integer types.

src/testsuite/vec_bcd_dummy.c, src/testsuite/vec_char_dummy.c, src/testsuite/vec_dummy_main.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_int32_dummy.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_pwr9_dummy.c
headers to generate short sequences of code that can be examined
via opbdump. This used both to evaulate correctness and performance.
2018-06-12 Steven Munroe <munroesj52@gmail.com>
* src/testsuite/vec_int128_dummy.c (test_vec_add256_1,
test_vec_add256_2, __test_msumudm, test_vec_cmul10cuq,
test_vec_cmul100cuq, test_vec_revbq): New Function.
update copyright.
* src/testsuite/vec_dummy_main.c: Update copyright.
* src/testsuite/vec_bcd_dummy.c: New File.
* src/testsuite/vec_char_dummy.c: New File.
* src/testsuite/vec_bcd_dummy.c: New File.
* src/testsuite/vec_int32_dummy.c: New File.
* src/testsuite/vec_int64_dummy.c: New File.
* src/testsuite/vec_pwr9_dummy.c: New File.
=> Update and refactor the "dummy" files. Dummy files use the pveclib

doc/pveclib-doxygen-pveclib.doxy, doc/pveclibmaindox.h, src/Makefile.am, src/Makefile.in, src/testsuite/arith128_print.c, src/testsuite/arith128_print.h, src/testsuite/arith128_test_bcd.c, src/testsuite/arith128_test_f32.c, src/testsuite/arith128_test_f32.h, src/testsuite/arith128_test_i128.c, src/testsuite/pveclib_test.c, src/testsuite/vec_f32_dummy.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_perf_f32.c, src/testsuite/vec_perf_f32.h, src/testsuite/vec_perf_i128.c, src/testsuite/vec_perf_i128.h, src/testsuite/vec_pwr9_dummy.c, src/vec_common_ppc.h, src/vec_f128_ppc.h, src/vec_f32_ppc.h
* doc/pveclib-doxygen-pveclib.doxy: Add vec_f32_ppc.h.
* src/Makefile.am: Add .libs/libpvecdummy.a ref.
* src/Makefile.am (libpvec_la_SOURCES): Add
testsuite/vec_f32_dummy.c.
* src/Makefile.am (pveclibinclude_HEADERS): Add vec_f32_ppc.h.
* src/Makefile.am (pveclib_test_SOURCES): Add
testsuite/vec_perf_f32.c, testsuite/vec_perf_i128.c,
testsuite/arith128_test_f32.c
* src/Makefile.am (pveclib_test_LDADD): Add .libs/libvecdummy.a
* src/Makefile.in: Regenerate.
* src/testsuite/arith128_print.c (print_vbool8, print_v4f32,
print_v4f32x, print_v4b32c, print_v4b32x, check_v4b32c_priv,
check_v4b32x_priv, check_v4f32_priv, check_v4f32x_priv):
New functions.
* src/testsuite/arith128_print.h (__VF_128 xfer): Rename.
* src/testsuite/arith128_print.h (TimeDeltaSec): New functions.
* …
=> Adding the float 32-bit stuff with an attempt on performance metrics.

src/testsuite/arith128_print.c, src/testsuite/arith128_print.h, src/testsuite/arith128_test_i64.c, src/testsuite/vec_int64_dummy.c, src/vec_f32_ppc.h, src/vec_int64_ppc.h
These are needed for the vec_f64_ppc.h vec_is* implementations that
avoid Floating-point exceptions.
* src/testsuite/arith128_print.c (print_v2f64, print_v2f64x,
print_v2b64c, print_v2b64x, check_v2b64c_priv,
check_v2b64x_priv, check_v2f64_priv, check_v2f64x_priv):
New functions.
* src/testsuite/arith128_print.h (print_v2f64, print_v2f64x,
print_v2b64c, print_v2b64x, check_v2b64c_priv,
check_v2b64x_priv, check_v2f64_priv, check_v2f64x_priv):
New extern function.
(check_v2b64c, check_v2b64x, check_v2f64, check_v2f64x):
New inline function.
* src/testsuite/arith128_test_i64.c (test_cmpud,
test_cmpud_all, test_cmpud_any, test_cmpsd, test_cmpsd_all,
test_cmpsd_any) New function.
(test_vec_i64): Call test_cmpud, test_cmpud_all,
test_cmpud_any, test_cmpsd, test_cmpsd_all, test_cmpsd_any.
* …
=> Complete the compare intrinsics for vector long (doubleword integer).

doc/pveclib-doxygen-pveclib.doxy, src/vec_f64_ppc.h, src/vec_int64_ppc.h
This commit is just the f64 header and doxy INPUT. Test cases and
configure.ac/Makefile.am changes will follow in part2/3.
* src/vec_f64_ppc.h: Add doxygen \file level intro.
(__f64_bool): Removed. Use vb64_t from <vec_common_ppc.h>.
(vec_absf64): New Function.
(vec_all_isinff64, vec_all_isnanf64, vec_all_isnormalf64,
vec_all_issubnormalf64, vec_all_iszerof64): New Functions.
(vec_any_isinff64, vec_any_isnanf64, vec_any_isnormalf64,
vec_any_issubnormalf64, vec_any_iszerof64): New Functions.
(vec_copysignf64): Update comments.
(vec_isinff64, vec_isnanf64, vec_isnormalf64,
vec_issubnormalf64, vec_iszerof64): Update implimentation and
comments.
* doc/pveclib-doxygen-pveclib.doxy (INPUT): Add vec_f64_ppc.h
to the Doxygen INPUT list.
* src/vec_int64_ppc.h: Remove commented out statements and …
=> Update vec_f64_ppc.h with new functions and prepare to publish.

src/Makefile.am, src/Makefile.in, src/testsuite/pveclib_test.c
install and make check.
* src/testsuite/pveclib_test.c:
Include <testsuite/arith128_test_f64.h>
(main): Add call to test_vec_f64.
* src/Makefile.am (libvecdummy_la_SOURCES):
Add testsuite/vec_f64_dummy.c.
(pveclibinclude_HEADERS): Add vec_f64_ppc.h.
(pveclib_test_SOURCES): Add testsuite/vec_perf_f64.c and
testsuite/arith128_test_f64.c.
* src/Makefile.in: Automake generated.
=> Final Makefile and test driver changes to activate vec_f64_ppc.h

src/testsuite/arith128_print.c, src/testsuite/arith128_print.h, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_perf_i128.c, src/testsuite/vec_perf_i128.h, src/vec_int128_ppc.h
updates and supporting arith128_print changes. Additional int128
specific performance and trace tests. And new dummy examples for
eyeballing the compiler generated code.
* src/vec_int128_ppc.h: Update doxygen comments.
* src/testsuite/arith128_print.c (print_vb128c, print_vb128x,
check_vb128c_priv, check_vb128x_priv): New functions.
* src/testsuite/arith128_print.h (print_vb128c, print_vb128x
check_vb128c_priv, check_vb128x_priv): New extern functions.
(check_vb128c, check_vb128x): New inline functions.
* src/testsuite/vec_int128_dummy.c (test_vec_subuqm,
test_vec_subcuq, test_vec_subeuqm_ecuq, test_vec_subuqm_cuq):
New Functions.
(test_vec_cmpeqsq, test_vec_cmpgesq, test_vec_cmpgtsq,
test_vec_cmplesq, test_vec_cmpltsq, test_vec_cmpequq,
test_vec_cmpgtuq, test_vec_cmpltuq, …
=> Part 2 of vec_int128_ppc.h update. Includes minor comment/doxygen

src/testsuite/arith128_test_i128.c
Completes this update.
* src/testsuite/arith128_test_i128.c (test_time_i128):
Change timed loop for mul10uq2x to cmul10ecuq.
Add timed l;oop for timed_muludq and timed_muludqx.
(test_subcuq, test_subecuq, test_subuq: New Functions.
(test_setbq): New function.
(test_cmpuq, test_cmpsq, test_cmpuq_all, test_cmpsq_all):
New functions.
(test_vec_i128): Add calls to test_subuq(), test_setbq(),
test_cmpuq(), test_cmpsq(), test_cmpuq_all(), and
test_cmpsq_all().
=> Part 3 add unit tests for new functions in vec_i128_ppc.h.

src/testsuite/vec_f64_dummy.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_pwr9_dummy.c, src/vec_f64_ppc.h, src/vec_int128_ppc.h
Found compile failures under _ARCH_PWR9 conditional due to wrong type.
Found compile failures for GCC6 (AT10) as vec_cmpne is not defined.
Runtime bad results due to early clobbler and reuse of carry VR in
inline __asm.
* src/testsuite/vec_f64_dummy.c (test_pred_f64_inf,
test_pred_f64_nan, test_pred_f64_normal,
test_pred_f64_subnormal, test_pred_f64_zero): Change return
type to vb64_t from vec_common_ppc.h.
[_ARCH_PWR9]: Remove __test_cmpnedp.
* src/testsuite/vec_int128_dummy.c (test_vec_cmul10uq_ecuq):
New Function.
* src/testsuite/vec_int64_dummy.c [_ARCH_PWR9]:
Remove __test_cmpneud.
* src/testsuite/vec_pwr9_dummy.c (test_vec_cmul10cuq_256_PWR9):
New Function.
[vec_cmpne] (__test_cmpnedp_PWR9, __test_cmpneud_PWR9):
New function.
* src/vec_f64_ppc.h (vec_isnanf64) [_ARCH_PWR9]: Correct …
=> Addtional small fixes for -mcpu=power9. After int128 commit.

doc/pveclib-doxygen-pveclib.doxy, src/vec_common_ppc.h, src/vec_f128_ppc.h
This will be in 3 parts. This is 1st part including
vec_f128_ppc.h itself and require changes to
doc/pveclib-doxygen-pveclib.doxy and src/vec_common_ppc.h.
I know vec_f128_ppc.h looks like patch but please treat it
like a new file for review.
* doc/pveclib-doxygen-pveclib.doxy [INPUT]: Add
$(SRCDIR)/src/vec_f128_ppc.h
* src/vec_common_ppc.h [__GNUC__ >= 4.8]:
Define vb128_t as __vector __bool __int128.
Otherwise __vector __bool unsigned int
* src/vec_f128_ppc.h: Update CR data.
Update doxygent \file description.
Add #include "vec_int128_ppc.h" and <vec_f64_ppc.h>.
Add \brief description for typedefs.
(__VF_128): Add \brief dscription for union members.
(vec_xfer_bin128_2_vui8t, vec_xfer_bin128_2_vui16t,
vec_xfer_bin128_2_vui32t, vec_xfer_bin128_2_vui64t.
vec_xfer_bin128_2_vui128t): New …
=> Introducing vec_f128_ppc.h with initial __float128 support.

src/testsuite/arith128_test_i64.c, src/testsuite/vec_int64_dummy.c, src/vec_int64_ppc.h
compares to return the appropriate vector bool.
* src/vec_int64_ppc.h (vec_cmpgtsd, vec_cmpequd, vec_cmpgeud,
vec_cmpgtud, vec_cmpneud): Change return type to vb64_t in
function prototype.
(vec_cmpeqsd): Change return type to vb64_t.
(vec_cmpequd): Change return type to vb64_t.
(vec_cmpgesd): Change return type to vb64_t.
(vec_cmpgeud): Change return type to vb64_t.
(vec_cmpgtsd): Change return type to vb64_t.
(vec_cmpgtud): Change return type to vb64_t.
(vec_cmplesd): Change return type to vb64_t.
(vec_cmpleud): Change return type to vb64_t.
(vec_cmpltsd): Change return type to vb64_t.
(vec_cmpltud): Change return type to vb64_t.
(vec_cmpnesd): Change return type to vb64_t.
(vec_cmpneud): Change return type to vb64_t.
(vec_cmpsd_all_ge, vec_cmpsd_all_gt, vec_cmpsd_all_ne, …
=> Per discussion in issue #29, this patch changes vec_int64_ppc.h

src/testsuite/arith128_print.c, src/testsuite/arith128_print.h, src/testsuite/arith128_test_f128.c, src/testsuite/arith128_test_f128.h, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_pwr9_dummy.c
Part2 including Unit tests, and dummy compile sources.
* src/testsuite/arith128_test_f128.c: New file.
* src/testsuite/arith128_test_f128.h: New file.
* src/testsuite/vec_f128_dummy.c: New file.
*src/testsuite/vec_pwr9_dummy.c: Include <vec_f128_ppc.h>.
(test_vec_isfinitef128_PWR9, test_vec_isinff128_PWR9,
test_vec_isnanf128_PWR9, test_vec_isnormalf128_PWR9,
test_vec_issubnormalf128_PWR9, test_vec_iszerof128_PWR9,
test_vec_all_normalf128_PWR9, test_vec_all_finitef128_PWR9,
test_vec_all_subnormalf128_PWR9, test_vec_all_inff128_PWR9,
test_vec_isinf_signf128_PWR9, test_vec_all_nanf128_PWR9,
test_vec_all_zerof128_PWR9): New Functions.
[ __FLOAT128_TYPE__] (test_sinf128_PWR9, test_cosf128):
New Functions.
[scalar_test_data_class] (__test_scalar_test_data_class_f128, …
=> Introduce vec_f128_ppc.h with initial __float128 support.

doc/pveclibmaindox.h, src/Makefile.am, src/Makefile.in, src/testsuite/pveclib_test.c
Includes the Makefile.ac updates to install vec_f128_ppc.h and
build/run the f128 specific unit tests. Also updated the \note on the
\mainpage for current status.
* doc/pveclibmaindox.h: Update \note with project status.
* src/Makefile.am (libvecdummy_la_SOURCES):
Add testsuite/vec_f128_dummy.c.
(pveclibinclude_HEADERS): Add vec_f128_ppc.h.
(pveclib_test_SOURCES): Add testsuite/arith128_test_f128.c.
* src/Makefile.in: Regenerated via automake.
* src/testsuite/pveclib_test.c:
Include <testsuite/arith128_test_f128.h>
(main): Call test_vec_f128().
=> Part3, Introduce vec_f128_ppc.h with initial __float128 support.

src/testsuite/arith128_test_f64.c, src/testsuite/vec_f64_dummy.c, src/testsuite/vec_pwr9_dummy.c, src/vec_f64_ppc.h
Simplify POWER8/POWER7 vector long int compares using pveclib
functions. Add appropriate unit tests.
* src/vec_f64_ppc.h: Update \file description.
Add \section f64_examples_0_0.
* src/vec_f64_ppc.h: Remove typedef __vbinary64. Use vf64_t
from vec_common_ppc.h.
(vec_unpack_longdouble, vec_pack_longdouble): Move down file
to preserve alphabetical order of function names.
(vec_all_isfinitef64): New function.
(vec_all_isinff64 [_ARCH_PWR9]): Use vec_test_data_class().
(vec_all_isnanf64 [_ARCH_PWR9]): Use vec_test_data_class().
(vec_all_isnormalf64 [_ARCH_PWR9]): Use vec_test_data_class().
(vec_all_issubnormalf64 [_ARCH_PWR9]):
Use vec_test_data_class().
(vec_any_iszerof64 [_ARCH_PWR9]): Use vec_test_data_class().
(vec_any_isfinitef64): New function.
(vec_any_isinff64 [_ARCH_PWR9]): Use …
=> Update vec_f64_ppc.h to use POWER9 test date class instructions.

src/testsuite/arith128_test_f64.c, src/vec_f64_ppc.h
Fixes after POWER9 testing in mambo.
* src/vec_f64_ppc.h (vec_all_isinff64 [_ARCH_PWR9]):
Correct DMCX const value for vec_test_data_class().
Should be 0x30 for +- Infinity.
(vec_all_issubnormalf64 [!_ARCH_PWR9]): Correct logic for
POWER8 vec_all_issubnormalf64 () code. Should be ALL (exponent < 1)
AND ALL (NOT 0.0).
(vec_any_isinff64 [_ARCH_PWR9]): Use vec_any_eq() for compare. Using
vec_all_eq was a pasto. Should use vec_any_eq to convert the
test_data_class to vector CC or int bool.
(vec_any_isnanf64 [_ARCH_PWR9]): Ditto.
(vec_any_isnormalf64 [_ARCH_PWR9]): Ditto.
(vec_any_issubnormalf64 [_ARCH_PWR9]): Ditto.
(vec_any_iszerof64 [_ARCH_PWR9]): Ditto.
* src/testsuite/arith128_test_f64.c (test_double_all_is):
Add test case for vec_all_issubnormalf64 for 2x
__DBL_DENORM_MIN__ values. …
=> Update vec_f64_ppc.h to use POWER9 test data class instructions.

src/Makefile.am, src/Makefile.in, src/testsuite/arith128_test_i16.c, src/testsuite/vec_int16_dummy.c, src/vec_int16_ppc.h
Plus POWER9 absolute difference, additional examples in the
\file doxygen text, and clean up doxygent comment alignment.
Add more unit tests to cover new functions.
* src/vec_int16_ppc.h: Update \File Description.
Add \section i16_endian_issues_0_0.
Add \section int16_examples_0_1.
Add \section int16_perf_0_0.
Clean up doxygen comment alignment for consistency.
For all function \brief descriptions add Latency and
throughput tables.
(vec_absduh, vec_mrgahh, vec_mrgalh, vec_mrgeh,
vec_mrgoh, vec_mulhsh, vec_mulhuh, vec_muluhm,
vec_vmrgeh, vec_vmrgoh): New Function.
* src/Makefile.am (libvecdummy_la_SOURCES):
Add testsuite/vec_int16_dummy.c
* src/Makefile.in: Regenerate from automake.
*src/testsuite/arith128_test_i16.c (test_muluhm, test_mulhsh,
test_mulhuh, test_mrgeoh, test_mrgahlh): New …
=> Update vec_int16_ppc.h to add merge even/odd and multiply high

src/testsuite/arith128_test_char.c, src/testsuite/vec_char_dummy.c, src/vec_char_ppc.h
Plus additional examples in the \file doxygen text.
Add latency info and clean up doxygent comment alignment.
Add more unit tests to cover new functions.
* src/vec_char_ppc.h: Update \File Description.
Add \section i8_endian_issues_0_0.
Add \section int8_perf_0_0.
Clean up doxygen comment alignment for consistency.
For all function \brief descriptions add Latency and
throughput tables.
(vec_mrgahb, vec_mrgalb, vec_mrgeb, vec_mrgob, vec_mulhsb,
vec_mulhub, vec_mulubm, vec_vmrgeb, vec_vmrgob): New Function.
* src/testsuite/arith128_test_char.c (test_mrgeob, test_mulhub,
test_mulhsb, test_mulubm): New Functions.
(test_vec_char): Add calls to test_mrgeob, test_mrgahlb,
test_mulhub, test_mulhsb, and test_mulubm.
* src/testsuite/vec_char_dummy.c (__test_sldo, test_vec_mergel,
test_vec_vmrglb): …
=> Update vec_char_ppc.h to add merge even/odd and multiply high

src/vec_common_ppc.h
Plus additional examples in the \file doxygen text.
* vec_common_ppc.h: Addtional Doxygen comments. Overview of
type nameing, transfer union, and endina const management macros.
* vec_common_ppc.h (CONST_VINT128_B, CONST_VINT8_B): New Macros.
=> Update vec_common_ppc.h to add byte const endian macros.

doc/pveclibmaindox.h
* doc/pveclibmaindox.h: Add "Hacker's Delight" to biblo.
(mainpage_endian_issues_1_1): Add subsection General Endian
Issues.
(mainpage_para_1_2_0): Add paragraph Vector Add Unsigned
Quadword Modulo example
(mainpage_para_1_2_1): Add paragraph Vector Multiply-by-10
Unsigned Quadword example. Add \ref i32_example_0_0_0 and
ref i32_example_0_0_1
=> Update main doc for endian with examples.

src/vec_f128_ppc.h, src/vec_int128_ppc.h, src/vec_int32_ppc.h, src/vec_int64_ppc.h
Additional examples in the \file doxygen text.
Add vec_absdud, vec_maxsd, vec_maxud, vec_minsd, vec_minud,
vec_mrgahd, vec_mrgald. Multiply doubleword in vec_int128_ppc.h
vec_int128_ppc.h add doubleword multiply high/low/even/odd.
Unit test in next update.
* src/vec_int64_ppc.h: Major update of header and dox text.
Add sections section i64_missing_ops_0_0,
i64_endian_issues_0_0, int64_examples_0_1.
[/@cond INTERNAL]: Move forward declares up for
vec_cmpgtsd, vec_cmpequd, vec_cmpgeud, vec_cmpgtud, vec_cmpneud.
[/@cond INTERNAL]: Add forward declarec for
vec_maxud, vec_minud, vec_permdi, vec_subudm, vec_xxspltd.
(vec_absdud, vec_maxsd, vec_maxud, vec_minsd, vec_minud,
vec_mrgahd, vec_mrgald): New functions.
(vec_mrged, vec_mrghd, vec_mrgld, vec_mrgod): Fix of endian
sensitive.
(vec_permdi): …
=> Update vec_int64_ppc.h to add permute/merge/splat/swap.

src/testsuite/arith128_test_i64.c
multiply high/low/even/odd. Endian sensitive. Fix whitespace.
*src/testsuite/arith128_test_i64.c: update copyright.
(db_vec_vsld, db_vec_vsrd, db_vec_vsrad): fix whitespace.
(test_vrld): New function.
(test_vec_vsld, test_vsrd, test_vsrad): Fix whitespace.
(test_mrghld, test_mrgeod, test_mrgahld): New function.
(test_splatd, test_xxspltd): New function.
(test_permdi, test_popcntd, test_clzd): Fix whitespace.
(test_muleud, test_muloud): Fix whitespace. Endian sensitive
const.
(test_mulhud, test_muludm, ): New Function.
(test_vmuleud, test_vmuloud): New Function.
(test_maxud, test_maxsd, test_minud, test_minsd): New Function.
(test_cmpud, test_cmpud_all, test_cmpud_any): Fix whitespace.
(test_cmpsd, test_cmpsd_all, test_cmpsd_any): Fix whitespace.
(test_vec_i64): Add calls to; test_xxspltd, …
=> Update arith128_test_i64.c with need tests for merge/rotate/splat

src/testsuite/arith128_test_i64.c, src/testsuite/vec_int64_dummy.c, src/vec_int64_ppc.h
A reccent compiler bug exposed a lack of test coverage for the
shift/rotate doubleword immediate operations. So added four test
variations to arith128_test_i64.c. Also added two compile tests for
vec_srdi to vec_int64_dummy.c. This exposed a pasto bug in shift
range check for vec_srdi.
* src/vec_int64_ppc.h (vec_srdi): Correct shift range check.
* src/testsuite/vec_int64_dummy.c (test_srdi_31, test_srdi_32):
New function.
* src/testsuite/arith128_test_i64.c (test_sradi, test_srdi,
test_sldi, test_rldi): New functions.
(test_vec_i64): Call test functions, test_sradi, test_srdi,
test_sldi, test_rldi.
=> Fixes and test case update for vec_int64_ppc.h

src/vec_int128_ppc.h, src/vec_int64_ppc.h
Also POWER9 and Endian fixes for vec_muludq, vec_mulluq.
Added vec_mulhuq. Specifics follow:
1) Unit tests for vec_sraqi detected a regression in GCC 8
in the code generation for builtins vec_sr, vec_sra, vec_vsrd,
vec_vsrad. This also failed unit tests for vec_srdi and vec_sradi.
Bill Schmidt is working the problem in Upstream (GCC9) and
will need a fix backported to GCC8 and AT12.
2) On testing the quadword multiplies (vec_muludq, vec_mulluq)
were not endian stable for POWER9. Corrected that using endian
stable merge and multiply doubleword operations. Also added vec_mulhuq
to support multiplicative inverse over quadword integers.
3) Added new quadword operations; vec_absduq,vec_avguq, vec_maxsq,
vec_maxuq, vec_minsq, vec_minuq, vec_mulhuq, vec_rlq, vec_rlqi,
vec_sldqi, vec_sraq, and …
=> More Fixes for vec_int64_ppc.h and functions for vec_int128_ppc.h.

src/testsuite/arith128_test_i128.c
Added new quadword unit tests; vec_absduq,vec_avguq, vec_maxsq,
vec_maxuq, vec_minsq, vec_minuq, vec_mulhuq, vec_rlq, vec_rlqi,
vec_sldqi, vec_sraq, and vec_sraqi.
* testsuite/arith128_test_i128.c (test_mulhuq): New function.
(test_vsraq, test_vsraqi, test_vrlq, test_vrlqi): New function.
(test_vsldq, test_vsldqi): New function.
(test_maxuq, test_maxsq): New function.
(test_minuq, test_minsq): New function.
(test_absduq, test_avguq): New function.
(test_vslq, test_vsrq, test_vslqi, test_vsrqi):
Additonal test cases. And white space
(main): Add calls for; test_vrlq, test_vrlqi. test_vsraq,
test_vsraqi, test_vsldq, test_vsldqi, test_mulhuq, test_maxuq,
test_maxsq, test_minuq, test_minsq, test_absduq, test_avguq.
=> P2 Unit tests for vec_int128_ppc.h. Specifics follow:

src/testsuite/vec_int128_dummy.c, src/testsuite/vec_pwr9_dummy.c
* testsuite/vec_int128_dummy.c (test_vec_add256_1,
test_vec_add256_2): Add __restrict__ to out parm.
(test_vec_add512_1, test_vec_add512_2): new function.
(test_vec_absduq, test_vec_avguq): New Function.
(__test_maxsq, __test_maxuq, __test_minsq, __test_minuq,
__test_minuq3, __test_minsq3): New Functions.
(test_vec_sraqi_0, test_vec_sraqi_4, test_vec_sraqi_7,
test_vec_sraqi_8, test_vec_sraqi_14, test_vec_sraqi_16,
test_vec_sraqi_31, test_vec_sraqi_48, test_vec_sraqi_68,
test_vec_sraqi_120, test_vec_sraqi_128, test_vec_sraqi_129):
New Functions.
(test_vec_sldqi_0, test_vec_sldqi_15, test_vec_sldqi_48,
test_vec_sldqi_52): New Functions.
(__test_mulhuq2): New Function.
(test_mul4uq): Formated.
(example_qw_convert_decimal) New Functions.
* testsuite/vec_pwr9_dummy.c ( __test_mulhuq_PWR9, …
=> P3 Fixes for vec_int128_ppc.h. Add compile tests

src/vec_bcd_ppc.h, src/vec_int128_ppc.h
where posible. Otherwise use inline asm where needed.
Turns out there are compiler bugs that prevent using the __builtin
functions on older compilers.
Also add a forward ref declare for vec_muludq in vec_int128_ppc.h.
This fixes a function not found when compiling -mcpu=power7.
* src/vec_bcd_ppc.h: #define vBCD_t.
(bcd_qauntize0): Format source.
(vec_pack_Decimal128): New function.
(vec_unpack_Decimal128): New function.
(vec_BCD2DFP): Use vBCD_t. Format source.
(vec_BCD2DFP [__GNUC__ < 5]) Else replace __asm with
__builtin_denbcdq. Use vec_unpack_Decimal128.
(vec_DFP2BCD): Use vBCD_t. Format source.
(vec_DFP2BCD [__GNUC__ < 5]) Else replace __asm with
__builtin_ddedpdq. Use vec_pack_Decimal128.
(vec_bcdadd): Use vBCD_t. Format source.
(vec_bcdadd [__GNUC__ < 7]) Else replace __asm with …
=> Cleanup vec_bcd_ppc.h. Use __builtin_bcdadd/bcdsub/denbcdq/ddedpdq

src/testsuite/arith128_test_bcd.c, src/testsuite/vec_bcd_dummy.c
Use vBCD_t type and fix formatting and white-space.
Add compile test for BCD and some DFP builtins.
* src/testsuite/arith128_test_bcd.c: Remove arith128.h include.
(db_vec_BC10ts2i128): Formatting and white-space.
(test_48): Ditto.
(test_cvtbcd2c100): Use vBCD_t. Formatting and white-space.
(test_bcd_addsub): Ditto.
(test_bcd_muldiv): Ditto.
* src/testsuite/vec_bcd_dummy.c (test_pack_Decimal128,
test_pack_Decimal128_cast, test_unpack_Decimal128,
test_unpack_Decimal128_cast, test_vec_BCD2DFP,
test_vec_DFP2BCD): New functions.
([__GNUC__ > 4] test__builtin_ddedpdq, test__builtin_denbcdq):
New functions.
([__GNUC__ > 4 [_ARCH_PWR8]] test__builtin_bcdadd,
test__builtin_bcdadd_eq, test__builtin_bcdsub,
test__builtin_bcdsub_eq, test__builtin_bcdmax,
test__builtin_bcdabsd): New functions. …
=> Cleanup arith128_test_bcd.c and vec_bcd_dummy.c.

src/vec_bcd_ppc.h
Added the widening radix conversion functions that are the basis for
the BCD to Binary conversions. Then defined the unsigned BCD to binary
functions. Will add the signed BCD convertions later (need the
appropriate set sign set bool operations first). Finally updated the
Doxygen comments to include the PowerISA history for BCD and DFP.
* src/vec_bcd_ppc.h: Update Doxygen description.
(bcd128_endian_issues_0_0, bcd128_perf_0_0): New section.
Update brief description of vBCD_t.
(bcd_qauntize0): Rename to vec_qauntize0_Decimal128.
(vec_qauntize0_Decimal128, vec_pack_Decimal128,
vec_unpack_Decimal128): Move down for alphabetical order.
(/@cond INTERNAL): Froward function declares.
(vec_bcdctub, vec_bcdctuh, vec_bcdctuw, vec_bcdctud,
vec_bcdctuq): New convert functions.
(vec_bcddiv): Use …
=> Complete the vec_bcd_ppc.h. unsigned BCD to binary operations.

src/testsuite/arith128_test_bcd.c, src/testsuite/vec_bcd_dummy.c, src/testsuite/vec_char_dummy.c, src/testsuite/vec_pwr9_dummy.c
Add unit tests for radix decimal to binary conversion.
Add unit tests for BCD to binary conversion.
Add BCD compile tests. Add vector char compile tests.
Add POWER9 compile test.
* src/testsuite/arith128_test_bcd.c (db_vec_ZN2i128):
New debug function.
(db_vec_BCD2i128, db_vec_BC10ks2i128, db_vec_BC100ms2i128):
Correct for endian.
(db_vec_BC10es2i128): Rename from db_vec_BC10ts2i128.
Use vec_vmuleud.
(test_48): Rename db_vec_BC10ts2i128 to db_vec_BC10es2i128.
(test_cvtbcd2c100): Rename vec_bcdctb100s to vec_rdxct100b.
(test_cvtbcd2c10k, test_cvtbcd2c100m, test_cvtbcd2c10e,
test_cvtbcd2c10e32, test_cvtbcfz2c100): New functions.
(test_bcdctub, test_bcdctuh, test_bcdctuw, test_bcdctud,
test_bcdctuq, test_zndctuq): New functions.
(test_vec_bcd): Add calls to test_cvtbcd2c10k, …
=> Complete compiler & unit tests for unsigned BCD to binary operations.

src/testsuite/arith128_test_bcd.c, src/testsuite/vec_bcd_dummy.c, src/testsuite/vec_pwr9_dummy.c
Added:
Signed BCD to vector __int128 conversion.
Extend/carry support for BCD add/sub.
BCD Multiply low/High combined (62-digit).
BCD Digit shifts.
* src/testsuite/arith128_test_bcd.c (db_vec_ZN2i128,
db_vec_BC10es2i128):
Code clean up.
(db_vec_bcddiv, db_vec_bcdmul, db_vec_bcdmulh, db_vec_cbcdmul):
New Functions.
(db_vec_bcdaddcsq, vec_copysign_Decimal128, db_vec_cbcdaddcsq,
db_vec_cbcdaddecsq, db_vec_bcdsubcsq): New Functions.
(test_bcd_muldiv): Update to use test_vec_bcddiv and
test_vec_bcdmul to switch between vec_bcd_ppc.h and local db_
implementations. Additional test cases.
(test_setb_bcdsq, test_setb_bcdinv, test_signbit_bcdsq,
test_bcdcpsgn, test_bcdctsq, test_bcds, test_bcdus,
test_bcdslrqi, test_bcdslruqi, test_bcd_mulh, test_bcd_cmul,
test_bcd_addcsq, test_bcd_subcsq, …
=> More vec_bcd_ppc.h compile and unit tests.

src/vec_bcd_ppc.h, src/vec_common_ppc.h
Clean up of Extend/carry support for BCD add/sub.
Fix a bug with borrow.
Added BCD compare for predicate and bool
New functions; vec_bcdcfz vec_bcdctz
Add shift and round, shift unsigned, Truncate, and
Unsigned truncate.
Latentcy estimates for new functions.
Add Doxygen exmaple of extented multiply.
* src/vec_bcd_ppc.h: Update Doxygen description.
[\section bcd128_details_0_0]: Added Some details of BCD
computation.
[\subsection bcd128_extended_0_1]: Added Preferred sign, zone,
and zero.
[\subsection bcd128_extended_0_2]: Was a section.
Corrected some of the code examples.
[\subsubsection bcd128_extended_0_2_1; Added Vector BCD
Multiply Quadword example.
(vbBCD_): New typedef for vector bool for BCD.
(vec_bcdsub): Forward ref prototype.
(vec_bcdaddcsq): Code improvements, reduced latency. …
=> More vec_bcd_ppc.h:

src/testsuite/arith128_test_bcd.c, src/testsuite/vec_bcd_dummy.c, src/testsuite/vec_pwr9_dummy.c
Update unit tests after change to bcdsub and related functions.
Added unit tests for new operations.
Added compile tests for new operations.
Added power9 target tests for new operations.
* src/testsuite/arith128_test_bcd.c (vec_copysign_Decimal128):
Prototype, disable for now.
(db_vec_cbcdaddcsq): Add debug printf. Update "borrow" test to
check for != BCD 0. Ditto for _ARCH_PWR7.
(db_vec_cbcdsubcsq): New function.
(test_bcd_subesqm): Correct unit tests results after changes.
(test_bcd_subecsq): Ditto.
(test_bcd_cadde256): Add unit tests.
(test_bcdcmpsq_p2, test_bcdcmpsq, test_bcdcmp_p2, test_bcdcmp,
test_bcdsetsgn, test_bcdcfz, test_bcdctz, test_bcdsr,
test_bcdtrunc, test_bcdutrunc, test_bcdtruncqi,
test_bcdutruncqi, test_bcdsrrqi, test_bcd_csube256):
New function.
(test_vec_bcd): Update …
=> More vec_bcd_ppc.h compile and unit tests:

src/testsuite/arith128_print.c, src/testsuite/arith128_print.h, src/testsuite/arith128_test_i128.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_pwr9_dummy.c, src/vec_int128_ppc.h
Added divide/modulo operations to to factor signed/unsigned vector
__int128 values to convert to BCD. The __int128 type can represent
integers up to 39 decimal digits while vector BCD can represent 31 (signed)
or 32 (unsigned) digits. The operations use the multiplicative inverse
to divide by 10**31 or 10*32) for the quotient. Then multiply and
subtract to isolate the remainder.
*src/vec_int128_ppc.h (\subsection int128_examples_0_1_2):
New Doxygen for "Converting Vector __int128 values to BCD".
(\subsection int128_examples_0_1_3): Renumbered from
\subsection int128_examples_0_1_2.
(vec_divsq_10e31, vec_divuq_10e31, vec_divuq_10e32,
vec_modsq_10e31, vec_moduq_10e31, vec_moduq_10e32):
New Functions.
* src/testsuite/arith128_test_i128.c (test_div_moduq_e32,
test_div_moduq_e31, …
=> More vec_bcd_ppc.h add factoring support to vec_int128_ppv.h:

src/vec_bcd_ppc.h, src/vec_char_ppc.h
More doxygent documentation. New functions for binary to BCD conversion.
Selective optimizations to leverage; POWER9, DFU, and compiler strength
redunction.
* src/vec_bcd_ppc.h (\subsection bcd128_extended_0_2):
Extended Precision computation with BCD. Replace todo with
overview text.
(\subsubsection bcd128_extended_0_2_0 Vector):  Add/Subtrace
with Carry/Extend example. Expand \todo with remaining issues
affecting extended BCD add/sub.
(\subsubsection bcd128_muldiv_0_2_1): Vector BCD
Multiply/Divide Quadword example.
Replaces bcd128_extended_0_2_1
(\subsubsection bcd128_convert_0_2_2): New subsubsection.
Vector BCD to/from Binary conversion.
(\paragraph bcd128_convert_0_2_2_1): New paragraph.
Vector Parallel conversion.
(\paragraph bcd128_convert_0_2_2_2): New paragraph.
Vector Parallel …
=> More vec_bcd_ppc.h add binary to BCD conversion:

src/vec_int128_ppc.h
Enable extended quadword long division by constant powers of 10.
This support conversion of multi-quadword binary integers to Decimal.
*src/vec_int128_ppc.h (\subsection int128_examples_0_1_3_0):
Add subsection header for "Extended Quadword multiply".
(\subsubsection int128_examples_0_1_3_1): New header and
description for "Quadword Long Division".
(vec_divuq_10e31, vec_divuq_10e32, vec_moduq_10e31,
vec_moduq_10e32, vec_subeuqm): New forward refs.
(vec_divudq_10e31, vec_divudq_10e32): New functions.
(vec_divuq_10e31): Correct comment.
(vec_modudq_10e31, vec_modudq_10e32): New functions.
(vec_moduq_10e31): Correct comment.
(vec_vmuleud, vec_vmuloud): Correct comment.
=> Add long division factoring support to vec_int128_ppv.h:

src/testsuite/vec_bcd_dummy.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_int16_dummy.c, src/testsuite/vec_pwr9_dummy.c
Enable extended quadword long division by constant powers of 10.
Addition compile tests and examples. Some examples are used as
performance tests.
* src/testsuite/vec_bcd_dummy.c (example_longbcdcf_10e32):
New function.
* src/testsuite/vec_int128_dummy.c (__test_divudq_10e31,
__test_divudq_10e32, __test_remudq_10e31, __test_remudq_10e32):
New function.
(example_longdiv_10e31, example_longdiv_10e32):
New example functions.
* src/testsuite/vec_pwr9_dummy.c (__test_divudq_10e31_PWR9,
__test_divudq_10e32_PWR9, __test_remudq_10e31_PWR9,
__test_remudq_10e32_PWR9): New functions.
(example_longdiv_10e31_PWR9): New example functions.
=> Add long division factoring support to vec_int128_ppc.h:

src/vec_bcd_ppc.h
Documnent extened BCD <-> binary conversions with examples.
Add a POWER9 specific optimization to vec_bcdctuq().
* src/vec_bcd_ppc.h: Improve Doxygen overview.
Cross reference BCD conversion and quadword long division
from vec_int128_ppc.h
[subsubsection bcd128_convert_0_2_3]: Add section
"Multiple precision BCD to/from Binary conversion"
[\paragraph bcd128_convert_0_2_3_0]: Add section
"Multiple precision BCD from Binary conversion"
[\paragraph bcd128_convert_0_2_3_1]: Add section
"Multiple precision BCD to Binary conversion"
(vec_bcdctuq [_ARCH_PWR9]): Optimization.
=> Add extended quadword BCD <> binary conversion to vec_bcd_ppc.h:

src/pveclib/vec_f128_ppc.h, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_pwr9_dummy.c
Float128 support is work in progress and Distro toolchains do not
include all Float128 backports provided by the Advance Toolchain.
So PVECLIB f128 operations that compile with AT may not compile with
the distro toolchain of the same GCC version.
This would be dissapointing for distros that claim power9 support.
This patch set insures that the Ubuntu 18.04 LTS toolchain can compile
and execute all pveclib vec_f128_ppc.h operations for -mcpu=power8/9.
*src/vec_f128_ppc.h (vec_all_isfinitef128, vec_all_isinff128,
vec_all_isnanf128, vec_all_isnormalf128,
vec_all_issubnormalf128, vec_all_iszerof128, vec_isfinitef128,
vec_isinf_signf128, vec_isinff128, vec_isnanf128,
vec_isnormalf128, vec_issubnormalf128, vec_iszerof128):
Add constrains "&& defined (__FLOAT128__) && (__GNUC__ > 7)"
before …
=> Fix vec_f128_ppc.h and dummmy for older compilers & without -mfloat128:

src/pveclib/vec_bcd_ppc.h, src/testsuite/arith128_print.c
Traced back to bad code generation for if (__builtin_bcdsub_gt)
tests in vec_bcdaddcsq, vec_bcdsubcsq.
Found a worrk around by replacing the if test (which is setting
the carry sign code) with vec_bcdcpsgn()
Also found check_vint384 was not printing 128-bit values in
the correct high to low order. Corrected this.
* src/pveclib/vec_bcd_ppc.h (vec_bcdaddcsq, vec_bcdsubcsq):
Simplify logic to avoid GCC9 code gen bug.
* src/testsuite/arith128_print.c
(print_vint384 [__BYTE_ORDER__]):
Print the 128-bit values in high to low order.
=> Test falures while testing Fedora 30 and GCC 9 compiler.

doc/pveclib-doxygen-pveclib.doxy, doc/pveclibmaindox.h, src/pveclib/vec_int128_ppc.h, src/pveclib/vec_int512_ppc.h
Header files ands doxygen inclues for new text.
* doc/pveclib-doxygen-pveclib.doxy (INPUT): Add
$(SRCDIR)/src/pveclib/vec_int512_ppc.h
* doc/pveclibmaindox.h: Mention vec_int512_ppc.h in intro.
* src/pveclib/vec_int128_ppc.h (int128_const_0_0_1):
Add doxygen subsection Quadword Integer Constants.
(int128_const_0_0_2): Add doxygen subsection for Support for
Quadword Integer Constants.
(int128_examples_0_1)): Update test_mul4uq example to match
current implementation.
(CONST_VUINT128_QxW,  CONST_VUINT128_QxD, CONST_VUINT128_Qx19d,
CONST_VUINT128_Qx18d, CONST_VUINT128_Qx16d): Defined quadword
helper macros.
* src/pveclib/vec_int512_ppc.h: New File.
=> Add vec_int512 files for multiple precision integer support.

README.md, src/pveclib/vec_int512_ppc.h, src/vec_int512_runtime.c, src/vec_runtime_DYN.c, src/vec_runtime_PWR7.c, src/vec_runtime_PWR8.c, src/vec_runtime_PWR9.c
Add the runtime library source supporting static and dynamic linkage.
* src/pveclib/vec_int512_ppc.h: Doxygen text updates after
review.
* README.md: Add -O3 and -mcpu to configure example.
* src/vec_int512_runtime.c: New file.
* scr/vec_runtime_PWR7.c: New file.
* src/vec_runtime_PWR8.c: New file.
* src/vec_runtime_PWR9.c: New file.
=> Add vec_int512 files for multiple precision quadword integer support.

src/pveclib/vec_f64_ppc.h, src/pveclib/vec_int128_ppc.h, src/pveclib/vec_int32_ppc.h, src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_print.h, src/testsuite/arith128_test_i32.c, src/testsuite/vec_f32_dummy.c, src/testsuite/vec_int32_dummy.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_pwr9_dummy.c
Fixes #82
Initially this was from missing multiply signed word implementation
for P7. But also hit a compiler bug where some built-ins where disabled
when I mixed -mcpu= and #pragma GCC target with different targets.
Specifically -mcpu=power7 and #pragma GCC target ("cpu=power8").
This seems to be Endian specific as P7 is BE only while P8 can be
either. Anyway. compiler folks are busy and will not spend cycles on a
bug that only impacts P7. So I added not conditionals to avoid this.
This should resolve issue #82.
* src/pveclib/vec_f64_ppc.h (vec_all_isfinitef64,
vec_all_isinff64, vec_all_isnanf64, vec_all_isnormalf64,
vec_all_issubnormalf64, vec_all_iszerof64
[__ORDER_LITTLE_ENDIAN__]): Test data built-ins only available
for LE.
* src/pveclib/vec_int128_ppc.h (vec_cmpsq_all_eq, …
=> Fix errors associaed with trying to use vector multiply word on P7.

src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_test_i64.c, src/testsuite/vec_int64_dummy.c
Added multiply-add operations to doubleword (POWER8/9) in support of multiple quadword multiply.
Used \copybrief so that doubleword operations, that are implemented in other headers, can appear in alphabetical order with other doubleword operations.
Added appropriate unit and compile tests.
* src/pveclib/vec_int64_ppc.h (vec_msumudm, vec_muleud,
vec_mulhud, vec_muloud, vec_muludm): Doxygen copybrief from
vec_int128_ppc.h.
(vec_vmadd2eud, vec_vmaddeud, vec_vmadd2oud, vec_vmaddoud,
vec_vmuleud, vec_vmuloud, vec_vmsumeud, vec_vmsumoud):
Doxygen copybrief from vec_int128_ppc.h.
(vec_vmaddeuw, vec_vmadd2euw, vec_vmaddouw, vec_vmadd2ouw):
New operations.
(vec_vmsumuwm): Doxygen text edits.
* src/testsuite/arith128_test_i64.c (test_vmaddeud,
test_vmaddoud): New Unit test.
(test_vmuleud): Add …
=> Optimizations for multiple quadword precision integer support (doubleword).

src/pveclib/vec_int512_ppc.h, src/testsuite/arith128_test_i512.c, src/testsuite/arith128_test_i512.h, src/testsuite/vec_perf_i512.c, src/testsuite/vec_perf_i512.h, src/vec_int512_runtime.c, src/vec_runtime_DYN.c
Added multi-quadword multiply-add operations optimized for (POWER7/8/9).
Used them to optimize larger multi-quadword multiply while carefully
use COMPILER_FENCE to avoid register presure and spill code.
Added appropriate unit, compile, anf performance tests.
* src/pveclib/vec_int512_ppc.h General doxygen text cleanup.
[i512_security_issues_0_0_2]: Remove todos from subsection.
[i512_Endian_issues_0_0]: Remove todos from section.
(__VEC_U_512x1): Add x2 field to union in support of madd.
(__VEC_U_4096x512): Add x4 field to union in support of add512.
[__VEC_EXPLICITE_FENCE_NOPS__]: Enable explicite NOPS to make
compiler fences visible.
(vec_mul256x256_inline): Add doxygen note.
Leverage madduq/madd2uq.
(vec_mul512x128_inline): Add doxygen note. Leverage madduq.
(vec_madd512x128a128_inline, …
=> Optimizations for multiple quadword precision integer support (multi-quadword).

src/Makefile.am, src/Makefile.in
Clean up build rules to generate libpvec.so and libpvecstatic.a and
eliminate unnecessary LTLIBRARIES.
Updated after review.
* src/Makefile.am [lib_LTLIBRARIES]: Remove libpveccommon.la,
libpvecPWR7.la,  libpvecPWR8.la, and libpvecPWR9.la
library builds. Add libpvecstatic.la.
Separate -mcpu target rules into vec_dynrt_*.lo and
vec_staticrt_*.lo, with and without -fpic.
[libpvecstatic_la_LIBADD]: Archive includes vec_staticrt_*.lo.
* src/Makefile.in: Regenerate.
=> Final Autotool changes to enable IFUNC build for pveclib run-time.

configure, configure.ac, src/Makefile.am, src/Makefile.in, src/vec_runtime_DYN.c
closes #96 
Adding the testprograms for configure tests broke out-of-source
builds. Add $srcdirs prefix to testprograms directory for each
AC_LANG_SOURCE.
Still trying to get the src/Makefile.am changes to stick. So
reapplying here.
And found a missing runtime function for src/vec_runtime_DYN.c
* configure.ac [AC_LANG_SOURCE]: Add $srcdir prefix to
testprograms dir.
* src/Makefile.am [lib_LTLIBRARIES]: Remove libpveccommon.la,
libpvecPWR7.la,  libpvecPWR8.la, and libpvecPWR9.la
library builds. Add libpvecstatic.la.
Separate -mcpu target rules into vec_dynrt_*.lo and
vec_staticrt_*.lo, with and without -fpic.
[libpvecstatic_la_LIBADD]: Archive includes vec_staticrt_*.lo.
* src/vec_runtime_DYN.c: Add extern for
vec_madd512x128a512_PWR7, vec_madd512x128a512_PWR8,
vec_madd512x128a512_PWR9. …
=> Autotool changes to enable out-of-source build for pveclib run-time.

src/pveclib/vec_int512_ppc.h
Moved most of the text to main page (doc/pveclibmaindox.h).
Rename section to "Building libraries for vec_int512_ppc".
Reduced remaining text to be specific to vec_int512_ppc.h.
* src/pveclib/vec_int512_ppc.h (i512_libary_issues_0_0):
Move contents to doc/pveclibmaindox.h. Add \ref to section
in doc/pveclibmaindox.h. Reduce details to be specific to
vec_int512_ppc runtime. Include refs to appropriate sections.
=> More doc updates for static/dynamic veclib run-time.

doc/pveclibmaindox.h
Clean up the main page documentation.
* doc/pveclibmaindox.h (Reference Documentation): Add link to
What is an indirect function (IFUNC)?
(POWER Vector Library Goals): Add ref to main_libary_issues_0_0
[main_libary_issues_0_0 Putting the Library into PVECLIB]
New section.
[mainpage_sub0 POWER Vector Library Goals]: Add mention of
run-time libraries with IFUNC resolvers.
[mainpage_sub1 How pveclib is different from compiler ...]:
Update text.
[mainpage_sub_1_1 What can we do about this?]:
Update text.
[mainpage_sub_1_1_2 Define multi-instruction sequences ...]:
Add section heading. Update text.
[mainpage_sub_1_1_3 Define new and useful operations]:
Add section heading. Update text.
[mainpage_sub_1_1_4 Leverage other PowerISA facilities]:
Add section heading. Update text. …
=> Doc update for Autotool changes for static/dynamic veclib run-time.

src/pveclib/vec_f64_ppc.h, src/pveclib/vec_int128_ppc.h, src/vec_int512_runtime.c
* src/pveclib/vec_f64_ppc.h: Include vec_int128_ppc.h> to
resolve forward refs.
* src/pveclib/vec_int128_ppc.h (vec_muludm, vec_mulhuq,
vec_muludq, vec_madduq, vec_madd2uq, vec_vmadd2oud,
vec_vmsumeud): Remove unused local vars.
* src/vec_int512_runtime.c (vec_mul128_byMN, vec_mul512_byMN):
Remove unused local vars.
=> Lint and -Wall clean-up for V1.0.4. Implementation files.

src/testsuite/vec_int128_dummy.c, src/testsuite/vec_int16_dummy.c, src/testsuite/vec_int32_dummy.c, src/testsuite/vec_int512_dummy.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_pwr9_dummy.c
* src/testsuite/vec_int128_dummy.c (__test_mulhuq,
test_mul128_MN): Remove unused local vars.
(example_qw_convert_decimal): Fix element extract type.
(example_print_vint128): GCC PR #96139.
* src/testsuite/vec_int16_dummy.c (__test_vmadduh_alt7):
Removed.
(__test_mrgeh2mrgoh): Initialize result for all paths.
* src/testsuite/vec_int32_dummy.c: Include vec_int128_ppc.h>
to resolve forward refs.
* src/testsuite/vec_int512_dummy.c (test_mulu2048x512,
test_mul1024x1024, test_mul1024x1024x, test_mul1024x1024y,
test_mulu2048x2048): Remove unused local vars.
* src/testsuite/vec_int64_dummy.c: Include vec_int128_ppc.h>
to resolve forward refs.
* src/testsuite/vec_pwr9_dummy.c: (__test_muludq_y_PWR9,
__test_mulhuq2_PWR9): Remove unused local vars.
(example_qw_convert_decimal_PWR9): Fix element …
=> Lint and -Wall clean-up for V1.0.4. Compile test files.

src/testsuite/arith128_print.c, src/testsuite/arith128_test_bcd.c, src/testsuite/arith128_test_i512.c, src/testsuite/vec_perf_i128.c, src/testsuite/vec_perf_i512.c
* src/testsuite/arith128_print.c (print_v2b64x, print_v2int64,
print_v2xint64): Work-around for GCC PR #96139.
* src/testsuite/arith128_test_bcd.c (db_vec_cbcdaddcsq,
test_longbcdct_10e32): Remove unused local vars.
* src/testsuite/arith128_test_i512.c (test_mul512x128_MN,
test_mul512x128, test_madd512x128, test_mul512x512_MN,
test_mul512x512, test_mul1024x1024, test_mul2048x2048_MN,
test_mul2048x2048): Remove unused local vars.
* src/testsuite/vec_perf_i128.c [PVECLIB_DISABLE_F128MATH]:
include local vars.
* src/testsuite/vec_perf_i512.c (timed_mul1024x1024by8,
timed_mul2048x2048_MN, timed_mul2048x2048by8,
timed_mul4096x4096_MN, timed_mul1024x1024, timed_mul2048x2048,
timed_mul512x512): Remove unused local vars.
=> Lint and -Wall clean-up for V1.0.4. Unit/perf test files.

Makefile.am, src/Makefile.am
While working on an early Debian package for the newer version of pveclib (1.0.4), I noticed that 'make dist' produces tarballs that have missing files. These missing files also cause 'make distclean' and 'make distcheck' to fail. This patch addresses these problems.
=> Add missing files to the distribution

Makefile.in, src/Makefile.in
* Makefile.in: Regenerate.
* src/Makefile.in: Regenerate.
=> Autotool cleanup for out-of-source build for pveclib run-time.

src/tipowof10.c
* src/tipowof10.c (tipowof10, tifrexpof10): Alias scalar
__int128 table to equivalent vector __int128.
=> Final clean-up for V1.0.4.

src/pveclib/vec_int32_ppc.h, src/testsuite/arith128_test_i32.c, src/testsuite/vec_int32_dummy.c
Vector Count Trailing Zeros instructions where added for POWER9.
These will be useful for implementing POWER10 Vector integer divide
and POWER9 Float128 round-to-odd operations on older processors. CTZ
can be implemented in a little as 3 instruction on POWER8.
* src/pveclib/vec_int32_ppc.h [@cond INTERNAL] Forward ref
vec_popcntw.
(vec_ctzw): New operation.
* src/testsuite/arith128_test_i32.c (test_ctzw): New Unit test.
(test_vec_i32): Call test_ctzw.
* src/testsuite/vec_int32_dummy.c (test_ctz_v1, test_ctz_v2,
test_ctz_v3, test_vec_ctzw): New compile tests.
=> Initial update for Count Trailing Zeros (CTZ) operations.

src/pveclib/vec_char_ppc.h, src/pveclib/vec_int16_ppc.h, src/testsuite/arith128_test_char.c, src/testsuite/arith128_test_i16.c, src/testsuite/vec_char_dummy.c, src/testsuite/vec_int16_dummy.c
Add byte and halfword forms of CTZ.
* src/pveclib/vec_char_ppc.h [@cond INTERNAL] Forward ref
vec_popcntb.
(vec_ctzb): New operation.
* src/pveclib/vec_int16_ppc.h [@cond INTERNAL] Forward ref
vec_popcnth.
(vec_ctzh): New operation.
* src/testsuite/arith128_test_char.c (test_ctzb):
New Unit test.
(test_vec_char): Call test_ctzb.
* src/testsuite/arith128_test_i16.c (test_ctzh):
New Unit test.
(test_vec_i16): Call test_ctzh.
* src/testsuite/vec_char_dummy.c (test_ctzb_v1, test_ctzb_v2,
test_ctzb_v3, test_ctzb, test_clzb): New compile tests.
* src/testsuite/vec_int16_dummy.c (test_ctzh_v1, test_ctzh_v2,
test_ctzh_v3, test_ctzh, test_clzh, test_popcnth):
New compile tests.
=> Continue update for Count Trailing Zeros (CTZ) operations.

src/pveclib/vec_int32_ppc.h, src/testsuite/arith128_test_i32.c, src/testsuite/vec_int32_dummy.c
Add alt vec_sums vec_sum2s forms. This improves double/quadword
clz, ctz, and popcnt performance.
* src/pveclib/vec_int32_ppc.h (vec_vsum2sw, vec_vsumsw):
New inline operations.
* src/testsuite/arith128_test_i32.c (test_sumsw, test_sum2sw):
New unit text functions.
(test_vec_i32): Call test_sumsw and test_sum2sw tests.
* src/testsuite/vec_int32_dummy.c (test_vec_sum2s,
test_vec_vsum2sw, test_vec_sums, test_vec_vsumsw):
New compile tests.
(test_ctz_v1, test_ctz_v2, test_ctz_v3): remove unused vars.
=> Continue (p3) update for Count Trailing Zeros (CTZ) operations.

src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_test_i64.c, src/testsuite/vec_int64_dummy.c
Vector doubleword implementation of ctz and improved clz and popcnt
for power7. Depends on ctz-p3.
* pveclib/vec_int64_ppc.h n[@cond INTERNAL]: Forward ref for
vec_popcntd.
(vec_clzd): Remove unnecessary cast. Replace vec_sum2s with
vec_vsum2sw.
(vec_ctzd): New inline operation.
(vec_popcntd): Replace vec_sum2s with vec_vsum2sw.
* src/testsuite/arith128_test_i64.c (test_ctzd) New unit test.
(est_vec_i64): Call test_ctzd.
* src/testsuite/vec_int64_dummy.c (test_ctzd_v1, test_ctzd_v2,
test_ctzd_v3, test_vec_ctzd): New compile tests.
=> Continue (p4) update for Count Trailing Zeros (CTZ) operations.

src/pveclib/vec_int128_ppc.h, src/testsuite/arith128_test_i128.c, src/testsuite/vec_int128_dummy.c
Vector quadword implementation of ctz and improved clz and popcnt.
Depends on ctz_p3 merge.
* src/pveclib/vec_int128_ppc.h [@cond INTERNAL]: Forward ref for
vec_popcntq.
(vec_clzq): Update doxygen latency for P8/P9.
(vec_clzq[_ARCH_PWR8]): Update implementation.
(vec_ctzq): New inline operation.
(vec_popcntq): Update doxygen latency for P8/P9.
(vec_popcntq[_ARCH_PWR9]): Add implementation.
(vec_popcntq[_ARCH_PWR8]): Update implementation.
Replace vec_sums with vec_vsumsw.
* src/testsuite/arith128_test_i128.c (test_ctzq):
New unit test.
(test_vec_i128): Call test_ctzq.
* src/testsuite/vec_int128_dummy.c (test_ctzq_v1, test_ctzq_v2,
test_ctzq_v3, test_ctzq_v4, test_ctzq_v5, test_vec_ctzq):
New compile tests.
=> Continue (p5) update for Count Trailing Zeros (CTZ) operations.

.travis.yml, README.md
Test on Ubuntu 20.04, using GCC 8, 9, AT 14.0 (GCC 10) and clang 10.
Notice this patch alone will not enable Travis CI on this project.
It also requires the owner of the repository to enable the tests on
https://travis-ci.org/github/open-power-sdk/pveclib
Signed-off-by: Tulio Magno Quites Machado Filho <tuliom@linux.ibm.com>
=> Add support for Travis CI

src/pveclib/vec_common_ppc.h, src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_test_i128.c, src/testsuite/arith128_test_i64.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_pwr9_dummy.c
The PowerISA does not support gather/scatter directly, but does provide
instructions to:
- Load/Store scalar elements directly to/from vector registers
- Combine and split these elements within vectors registers.
- Transfer scalar elements directly from vectors to GRPs for effective
address calculations (PWR8+).
This is sufficient to implement Gather/Scatter operations small enough
to be inline functions. Quickly noted that some instructions have no
built-in support. So provided inline asm implementations where needed.
This is a rethink and replacement for the 1st implementations. After
implementing float double and integer word form, I see a number of
misconceptions and poor naming choices that should be rectified.
- Change to Vector Gather-Load and Vector Scatter Store naming.
- Change …
=> Initial support for Gather/Scatter ops. 2nd try for doubleword int.

src/pveclib/vec_f64_ppc.h, src/testsuite/arith128_test_f64.c, src/testsuite/vec_f64_dummy.c
Rationalizing the mnemonics and operation names for "Vector Load
Scalar Float Double Indexed" and "Vector Store Scalar Float Double
Indexed" Also some clean up for -Werror -Wall compiles.
* src/pveclib/vec_f64_ppc.h: Rename vec_vlsfdux to vec_vlxsfdx.
Rename vec_vstsfdux to vec_vstxsfdx.
(vec_vlxsfdx): Change Doxygen full name to
"Vector Load Scalar Float Double Indexed".
Change "m' constraint to EA (rb+ra).
(vec_vstxsfdx): Change Doxygen full name to
"Vector Store Scalar Float Double Indexed".
* src/testsuite/arith128_test_f64.c: Rename vec_vlsfdux to
vec_vlxsfdx and vec_vstsfdux to vec_vstxsfdx.
(test_stvgdfdx): Remove unused variables; i1, j0.
(test_f64_matrix_transpose): Remove unused variable rc.
(test_f64_matrix_gather_transpose): Reformate.
Remove unused variables; xt, k, l, rc. …
=> Initial support for Gather/Scatter ops, 2nd pass for double float.

src/pveclib/vec_int32_ppc.h, src/testsuite/arith128_test_i32.c, src/testsuite/vec_int32_dummy.c
This is the integer word variant of Gather/Scatter.
The Gathers have three vector result forms:
- Words zero extented to unsigned doubleword integers.
- Words signed extended to signed doubleword integers.
- Words as unsigned word integers.
The doubleword results take signed doubleword offsets/indexes.
The Scatter has two vector source forms;
- Wnsigned Doublewords where only the low order words is stored.
- Unsigned words where all 4 words are stored.
Doubleword sources take vector signed doubleword offsets/indexes,
while word sources take vector signed word offsets/indexes,
There are also forms where offsets are provided as 2/4 const scalar
offsets. These are optimized for const offsets but are also used
in the implementation of the vector offset/index forms.
* …
=> Initial support for Gather/Scatter ops, 1st pass for int32.

src/pveclib/vec_f32_ppc.h, src/testsuite/arith128_test_f32.c, src/testsuite/arith128_test_f32.h, src/testsuite/vec_f32_dummy.c, src/testsuite/vec_perf_f32.c, src/testsuite/vec_perf_f32.h
This is the Single Precision Float variant of Gather/Scatter.
The Gathers have three vector result forms:
- Float single words expanded to Float Double as vector double.
- Float single words as vector float.
The doubleword results take signed doubleword offsets/indexes.
The word results take signed word offsets/indexes.
The Scatter has two vector source forms;
- Vector Double rounded and converted to float single stored as words.
- Vector Float where all 4 words are stored are float single.
Doubleword sources take vector signed doubleword offsets/indexes,
while word sources take vector signed word offsets/indexes,
There are also forms where offsets are provided as 2/4 const scalar
offsets. These are optimized for const offsets but are also used
in the implementation of the vector …
=> Initial support for Gather/Scatter ops, 1st pass for f32.

src/Makefile.am, src/Makefile.in, src/vec_int512_runtime.c
GCC does not honor __attribute__((flatten)) for fpic or fpie.
In effect the inlining is disabled for extern functions and PIC style
function calls are generated. For example; vec_mul512x128 and vec_madd512x128a512 
are used in the implementation of vec_mul512x512. vec_mul512x512 and
vec_madd512x512a512 are used in the implementations of vec_mul1024x1024
and vec_mul2048x2048.
If these calls are not fully inlined, the result is;
- parameters are restricted to the ABI defined VRs,
- register allocation is more restricted,
- all volatile VRs/VSRs are killed across calls,
- volitile VSRs can not be effectively used as temporaries.
- non-volitile VSRs may be saved to the register save-area and are
exposed to cache based side channel attack.
This hurts performance and can expose intermediate …
=> Fixes for issue #129.

.travis.yml, src/pveclib/vec_int128_ppc.h, src/testsuite/arith128_test_i128.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
Use P10 instructions for P10 specific implementations of existing
operations.  Add new operations based on P10 instructions as needed.
Add associated compile and unit tests.
* src/pveclib/vec_int128_ppc.h (vec_vsldbi): Forward ref.
(vec_msumcud): New inline operation.
(vec_mulhud [_ARCH_PWR10]): Add P10 specific implementation.
(vec_muludm): Update Doxygen comments.
[_ARCH_PWR10]: Add P10 specific implementation.
(vec_rlq [_ARCH_PWR10]): Add P10 specific implementation.
(vec_rlqi [_ARCH_PWR10]): Add P10 specific implementation.
(vec_slq [_ARCH_PWR10]): Add P10 specific implementation.
(vec_slqi [_ARCH_PWR10]): Add P10 specific implementation.
(vec_sraq [_ARCH_PWR10]): Add P10 specific implementation.
(vec_sraqi [_ARCH_PWR10]): Add P10 specific implementation.
(vec_srq [_ARCH_PWR10]): Add …
=> Exploit P10 instructions in existing operations.

src/pveclib/vec_int128_ppc.h, src/testsuite/arith128_test_i128.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_pwr10_dummy.c
Use P10 instructions for P10 specific implementations of existing
shift left double quadword and new shift left/right by bits immediate
operations.
Found that the new vrlq, vslq, vsraw, vsrq instructions use vector
bits 57:63 for shift count where original Altivec Octet and Bit shifts
used bits 121:127.  So P10 needs shift count adjusted (xxsplatd)
for P10.  Also updated vec_sldqi to leverage vsldbi for P10.
Add associated compile and unit tests.
* src/pveclib/vec_int128_ppc.h (vec_rlq [_ARCH_PWR10]):
Use vec_splatd() to adjust shift count for P10.
* (vec_sldqi): Add code to special case Octet, (shb < 8),
and (shb > 7) cases for P10 using vsldbi.
(vec_slq [_ARCH_PWR10]): Use vec_splatd() to adjust shift
count for P10.
(vec_sraq [_ARCH_PWR10]): Use vec_splatd() to adjust shift
count for …
=> Exploit P10 instructions in existing and new quad shift operations.

src/pveclib/vec_char_ppc.h, src/pveclib/vec_f128_ppc.h, src/pveclib/vec_f32_ppc.h, src/pveclib/vec_f64_ppc.h, src/pveclib/vec_int128_ppc.h, src/pveclib/vec_int16_ppc.h, src/pveclib/vec_int32_ppc.h, src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_test_char.c, src/testsuite/arith128_test_f32.c, src/testsuite/arith128_test_f64.c, src/testsuite/arith128_test_i16.c, src/testsuite/arith128_test_i32.c, src/testsuite/arith128_test_i64.c, src/testsuite/vec_char_dummy.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_f32_dummy.c, src/testsuite/vec_f64_dummy.c, src/testsuite/vec_int16_dummy.c, src/testsuite/vec_int32_dummy.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
Use P10's expand mask instructions for set bool (setb) from sign for
P10 specific implementations of existing and new vec_setb_* operations.
This includes the existing vec_setb_sq (__int128) and vec_setb_qp
(float128) operations, plus new operations for integer signed
long long, int, short and char and floating-point single and double.
* src/pveclib/vec_char_ppc.h (vec_setb_sb): New operation.
* src/pveclib/vec_f128_ppc.h (vec_setb_qp [_ARCH_PWR10]):
Use vexpandqm for POWER10.
* src/pveclib/vec_f32_ppc.h (vec_setb_sp): New operation.
* src/pveclib/vec_f64_ppc.h (vec_setb_dp): New operation.
* src/pveclib/vec_int128_ppc.h (vec_setb_sq [_ARCH_PWR10]):
Use vexpandqm for POWER10.
* src/pveclib/vec_int16_ppc.h (vec_setb_sh): New operation.
* src/pveclib/vec_int32_ppc.h (vec_setb_sw): New …
=> Exploit P10 expand mask instructions in existing and new operations.

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_pwr9_dummy.c
Also work around GCC PR 100085.
Use P9's xsiexpqp, xsxexpqp, xsxsigqp instructions plus provide
equivalent P8 implementations. In the process noticed code gen issues
document in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100085.
So updated and augmented the vec_xfer_bin128_2_ operations with
in-line asm to work around the bad code generated for power8/LE.
In some case combined the xfer with logical operations to avoid
redundent instructions.
* src/pveclib/vec_f128_ppc.h (vec_and_bin128_2_vui32t,
vec_andc_bin128_2_vui32t, vec_andc_bin128_2_vui128t):
New transfer with logical and operations.
(vec_xfer_bin128_2_vui8t [!defined (_ARCH_PWR9)]):
Add inline xfer (xxlor/vmr).
(vec_xfer_bin128_2_vui32t [!defined (_ARCH_PWR9)]):
Add inline xfer (xxlor/vmr).
(vec_xfer_bin128_2_vui128t [!defined …
=> Exploit P9 extract/insert instructions operations.

src/pveclib/vec_f128_ppc.h, src/pveclib/vec_f32_ppc.h, src/pveclib/vec_f64_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/arith128_test_f32.c, src/testsuite/arith128_test_f64.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_f32_dummy.c, src/testsuite/vec_f64_dummy.c, src/testsuite/vec_pwr9_dummy.c
Exploit P9 extract/insert instructions operations.
Use P9's xviexp[d|s]p, xvxexp[d|s]p, xvxsig[d|s]p instructions plus
provide equivalent P8 implementations.
* src/pveclib/vec_f32_ppc.h (vec_xviexpsp, vec_xvxexpsp,
vec_xvxsigsp): New inline functions.
* src/pveclib/vec_f64_ppc.h (vec_xviexpdp, vec_xvxexpdp,
vec_xvxsigdp): New inline functions.
* src/testsuite/arith128_test_f32.c [__FLOAT_ZERO,
__FLOAT_NZERO, __FLOAT_ONE, __FLOAT_NONE, __FLOAT_MAX,
__FLOAT_NMAX, __FLOAT_SUB, __FLOAT_NSUB, __FLOAT_NINF,
__FLOAT_NSNAN, __FLOAT_TRUE,__FLOAT_HIDDEN]: Define.
(test_extract_insert_f32): New unit test function.
(test_vec_f32): Call test_extract_insert_f32 from driver.
* src/testsuite/arith128_test_f32.c [__DOUBLE_ZERO,
__DOUBLE_NZERO, __DOUBLE_ONE, __DOUBLE_NONE, __DOUBLE_MAX,
__DOUBLE_NMAX, …
=> Power9 xviexpdp

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
Use P9/10's compare instructions plus provide equivalent P8 inline
implementations. This is part 1 with EQ and GT compares.
Implementations for other (GE, LE, LT, NE) compares to follow.
The P8 line operation show a 4+x performance improvement over
the libgcc soft-float equivalents.
* src/pveclib/vec_f128_ppc.h: Update doxygen intro.
[f128_softfloat_0_0 Vector]: New doxygen section.
(vec_sel_bin128_2_bin128): New operation.
(vec_xfer_bin128_2_vui32t): Work around for GCC PR 100085.
(vec_all_isnanf128 [_ARCH_PWR8]): P8 optimization.
(vec_cmpeqtoqp, vec_cmpequzqp, vec_cmpeqtoqp): New inline
operations tuned for P8/9/10.
(vec_cmpqttoqp, vec_cmpgtuzqp, vec_cmpgttoqp): New inline
operations tuned for P8/9/10.
(vec_self128): New flotat128 select operation.
(vec_setb_qp): Correct parm name for …
=> Exploit P9/10 Float128 compare instructions plus P8 equivalants.

src/pveclib/vec_f32_ppc.h, src/pveclib/vec_f64_ppc.h
Use P9's built-ins; vec_insert_exp, vec_extract_exp, vec_extract_sig
if available.
* src/pveclib/vec_f32_ppc.h (vec_xviexpsp [vec_insert_exp]):
Use built-in vec_insert_exp if available.
(vec_xvxexpsp): Correct doxygen text.
[vec_extract_exp]: Use built-in vec_extract_exp if available.
(vec_xvxsigsp): Correct doxygen text.
[vec_extract_sig]: Use built-in vec_extract_sig if available.
* src/pveclib/vec_f64_ppc.h (vec_xviexpdp [vec_insert_exp]):
Use built-in vec_insert_exp if available.
(vec_xvxexpdp): Correct doxygen text.
[vec_extract_exp]: Use built-in vec_extract_exp if available.
(vec_xvxsigdp): Correct doxygen text.
[vec_extract_sig]: Use built-in vec_extract_sig if available.
=> Exploit P9 extract/insert instructions operations. Update

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
Complete the remaining boolian compares (ge, le, lt, ne).
* src/pveclib/vec_f128_ppc.h (vec_cmpgetoqp, vec_cmpgeuzqp,
vec_cmpgeuqp): New inline operations.
(vec_cmpgetoqp, vec_cmpgeuzqp, vec_cmpgeuqp):
New inline operations.
(vec_cmpgttoqp, vec_cmpgtuzqp, vec_cmpgtuqp):
Fix doxygen text.
(vec_cmpletoqp, vec_cmpleuzqp, vec_cmpleuqp):
New inline operations.
(vec_cmplttoqp, vec_cmpltuzqp, vec_cmpltuqp):
New inline operations.
(vec_cmpnetoqp, vec_cmpneuzqp, vec_cmpneuqp):
New inline operations.
* src/testsuite/arith128_test_f128.c (test_cmpgt_f128):
Add new unit tests.
(test_cmplt_f128, test_cmpge_f128, test_cmple_f128,
test_cmpne_f128): Add new unit test functions.
(test_vec_f128): Call new unit test functions.
* src/testsuite/vec_f128_dummy.c (test_scalar_test_neg,
test_scalar_cmpto_exp_gt, …
=> Part2 P9/10 Float128 compare instructions plus P8 equivalants.

.travis.yml
* .travis.ylm: Add -mcpu=power9 build.
=> Add a -mcpu=power9 for AT14.0 build to Travis

src/pveclib/vec_int128_ppc.h, src/testsuite/vec_pwr10_dummy.c
Updates for vec_int128_ppc.h to use new Vector Compare
signed/unsigned Quadword instructions. Requires GCC10 for in-line
assembler and GCC 11.1 for altivec.h generic and predicate support.
Other minor performance updates.
* src/pveclib/vec_int128_ppc.h (vec_cmpequq [_ARCH_PWR10]):
Use vec_cmpeq() for GCC11. Otherwise inline asm "vcmpequq".
[!_ARCH_PWR8]: Simplify code for POWER7 and earlier.
(vec_cmpgesq [_ARCH_PWR10]): Use vec_cmpge() for GCC11.
Otherwise inline asm "vcmpgtsq" and "vnor".
(vec_cmpgeuq [_ARCH_PWR10]): Use vec_cmpge() for GCC11.
Otherwise inline asm "vcmpgtuq" and "vnor".
(vec_cmpgtsq [_ARCH_PWR10]): Use vec_cmpgt() for GCC11.
Otherwise inline asm "vcmpgtsq".
(vec_cmpgtuq [_ARCH_PWR10]): Use vec_cmpgt() for GCC11.
Otherwise inline asm "vcmpgtuq".
(vec_cmplesq …
=> Enable POWER10 quadword integer compare instructions.

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/vec_f128_dummy.c
Complete the remaining predicate compares (all_eq, all_gt, all_lt,
all_ge, all_le, all_ne). Also add bool and predicate unordered
compares to be used with IEEE complient compares.
Finally fixed latent bugs in the POWER10 inline asm.
* src/pveclib/vec_f128_ppc.h (vec_all_isnanf128, vec_isnanf128,
vec_isunorderedf128): Forward declares.
(vec_all_isunorderedf128): New inline operation.
(vec_cmpequqp, vec_cmpgeuqp, vec_cmpgtuqp, vec_cmpleuqp,
vec_cmpleuqp, vec_cmpneuqp [_ARCH_PWR8]):
Use vec_isunorderedf128().
(vec_cmpgetoqp [_ARCH_PWR10]): Use xscmpgeqp instruction.
(vec_cmpgeuzqp [_ARCH_PWR10]): Use xscmpgeqp instruction.
(vec_cmpgeuqp [_ARCH_PWR10]): Use xscmpgeqp instruction.
(vec_cmpletoqp [_ARCH_PWR10]): Use xscmpgeqp instruction.
(vec_cmpleuzqp [_ARCH_PWR10]): Use xscmpgeqp …
=> Part3 P9/10 Float128 compare instructions plus P8 equivalants.

src/pveclib/vec_int128_ppc.h, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_pwr10_dummy.c
The compiler support for quadword integer intrinsics missed the
GCC 11.1 release. So must change the conditional compile guards
to expect GCC 11.2. Pluse some minor clean up.
Add new operations in support for vec_f128_ppc.h work.
* src/pveclib/vec_int128_ppc.h (vec_negsq, vec_selsq):
Function prototype forward refs for new operations.
(vec_abssq): New inline operation.
(vec_cmpequq, vec_cmpgesq, vec_cmpgeuq, vec_cmpgtsq,
vec_cmpgtuq, vec_cmplesq, vec_cmpleuq, vec_cmpltsq,
vec_cmpltuq, vec_cmpneuq [_ARCH_PWR10]):
Adjust conditional compile gaurds for GCC to
((__GNUC__ == 11) && (__GNUC_MINOR__ >= 2)).
(vec_cmpsq_all_ge, vec_cmpsq_all_gt, vec_cmpsq_all_le,
vec_cmpsq_all_lt, vec_cmpsq_all_ne, vec_cmpuq_all_eq,
vec_cmpuq_all_ge, vec_cmpuq_all_gt, vec_cmpuq_all_le,
vec_cmpuq_all_lt, …
=> Part 2. Exploit P10 instructions in existing int128 operations.

src/pveclib/vec_int128_ppc.h, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_pwr10_dummy.c
Build with GCC 11.1 was broken because of some implicit type conversions,
causing the compilation to fail with many errors like this:
```
$ pveclib/src/pveclib/vec_int128_ppc.h:4610:22: error: incompatible types when
assigning to type ‘vui128_t’ {aka ‘__vector(1) __int128 unsigned’} from type
‘vb128_t’ {aka ‘__vector(1) __int128’}
4610 |               vsgn = vec_setb_sq (vra);
|                      ^~~~~~~~~~~
```
Some of these were caused by testsuite wrappers with different signatures from
their inner functions and also some missing casts on the definitions of
vec_sraq, vec_sraqi, and vec_setb_ncq.
=> Fix type conversions between vector types

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/pveclib_perf.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_perf_f128.c, src/testsuite/vec_perf_f128.h, src/testsuite/vec_pwr9_dummy.c
Power9 and Power8 equivalent operations for double float, signed
and unsigned doubleword conversion to quad-precision float.
Include compile, unit, performance tests.
* src/pveclib/vec_f128_ppc.h: Updates to doxygen.
[f128_softfloat_0_0_2]: Quad-Precision converts for POWER8.
(vec_xsiexpqp): Forward prototype.
(vec_xscvdpqp, vec_xscvsdqp, vec_xscvudqp): New operations.
* src/testsuite/arith128_test_f128.c (db_vec_xscvdpqp):
New debug only function.
(test_convert_dpqp, test_convert_udqp, test_convert_sdqp):
New unit test fuinctions.
(test_vec_f128): Add calls to new unit tests above.
* src/testsuite/vec_perf_f128.c
(f64_one, f64_fact2, f64_fact3, f64_fact4, f64_fact5,
f64_fact6, f64_fact7, f64_fact8, f64_fact9, f64_fact10,
invfact1_2, invfact3_4, invfact5_6, invfact7_8, invfact9_10):
New …
=> P9/10 Float128 convert instructions plus P8 equivalants. P1

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/pveclib_perf.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_perf_f128.c, src/testsuite/vec_perf_f128.h, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
Major doxygen update with the "story so far".
Some doxygen clean-up.
Addtional Power9 and Power8 equivalent quad-precision conversion
operations.
Includes compile, unit, performance tests.
* src/pveclib/vec_f128_ppc.h: Update doxygen intro.
Add subsections; f128_softfloat_IRRN_0_0, and
f128_softfloat_0_0_2_2
(vec_xsxexpqp, vec_xsxsigqp): Add forward static inline.
(vec_xor_bin128_2_vui32t): New transfer operation.
(vec_cmpneuzqp): Correct doxygen description.
(vec_cmpqp_exp_eq, vec_cmpqp_exp_gt, vec_cmpqp_exp_lt,
vec_cmpqp_exp_unordered): New compare exponent operations.
(vec_nabsf128, vec_negf128, vec_xscvqpdpo, vec_xscvqpudz,
vec_xscvqpuqz): New operations.
(vec_xscvudqp): Correct POWER7 only implementation.
(vec_xscvsqqp, vec_xscvuqqp):  New operations.
* …
=> P9/10 Float128 convert instructions plus P8 equivalants. P2

src/testsuite/pveclib_perf.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_perf_f128.c, src/testsuite/vec_perf_f128.h
PVECLIB compile fails for GCC12 as reported:
https://github.com/advancetoolchain/advance-toolchain/pull/2275
Seems GCC V12 wants to disable explicitly enabling -many for
assembly. vec_f128_dummy.c had some perf code trying to compare
hard/soft-float performance using in-line __builtin_cpu_supports.
This trick requires -many to work. So disable them for now, but
will need something similar for perf testing the round-to-odd
implementations.
* src/testsuite/pveclib_perf.c: Add commment about disabling
some tests until the F128 round-to-odd implementations are
ready.
* src/testsuite/vec_f128_dummy.c (test_scalar_add128,
test_scalar_div128, test_scalar_mul128, test_scalar_sub128):
Remove __builtin_cpu_supports code. Conditionally Disable the
lot.
* src/testsuite/vec_perf_f128.c …
=> Fix problems for GCC V12 turning off -many

src/testsuite/vec_pwr9_dummy.c
One assignment to 'result' was using a cast to vb128_t, causing build errors
with GCC 12.
* src/testsuite/vec_pwr9_dummy.c
(test_convert_qpuqz_PWR9): Cast to vui128_t when assigning result
Signed-off-by: Matheus Castanho <msc@linux.ibm.com>
=> Fix incompatible type assignment

src/pveclib/vec_common_ppc.h, src/pveclib/vec_f32_ppc.h, src/pveclib/vec_f64_ppc.h, src/testsuite/arith128_test_f32.c, src/testsuite/arith128_test_f64.c, src/testsuite/vec_f64_dummy.c, src/testsuite/vec_int128_dummy.c
* src/pveclib/vec_common_ppc.h (__VEC_U_128):
Correct typedef for member i128.
* src/pveclib/vec_f32_ppc.h (vec_xvxexpsp):
Remove unused const var zero.
* src/pveclib/vec_f64_ppc.h (vec_xviexpdp):
Remove unused var t128.
* src/testsuite/arith128_test_f32.c (test_extract_insert_f32):
Remove unused var sigs.
* src/testsuite/arith128_test_f64.c (test_extract_insert_f64):
Remove unused var sigs.
* src/testsuite/vec_f64_dummy.c:
Move #endif matching #ifdef _ARCH_PWR8 up.  
Guard the vector double tests while leaving the gather/scatter matrix transpose test enabled for all targets.
* src/testsuite/vec_int128_dummy.c
(example_print_vint128 [__GNUC__ > 9]): long long format
warn corrected after GCC 9.
=> General cleanup for Wall warnings and typos.

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/pveclib_perf.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_perf_f128.c, src/testsuite/vec_perf_f128.h, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
Power9 provide round to odd versions for the QP arithmetic operations.
This patch provides P9/8 implementation for add/sub QP with round
to odd. Includes compile, unit, and performance tests.
* src/pveclib/vec_f128_ppc.h [doxygen brief]:
Added micro-benchmark data. Other clean up.
[doxygen f128_softfloat_0_0]: Clarifications.
[doxygen f128_softfloat_0_0_0]: Clarifications.
[doxygen f128_softfloat_IRRN_0_0]: Clarifying Note.
[doxygen f128_softfloat_IRRN_0_1]:
Improve internal representation (IR) overview.
[doxygen f128_softfloat_IRRN_0_2]:
Expond on how the IR impacts rounding.
[doxygen f128_softfloat_0_0_3_2]:
Add overview of Add Quad-Precision with Round-to-Odd.
[doxygen f128_softfloat_0_0_3_3]:
Add overview of Subract Quad-Precision with Round-to-Odd.
[__clang__]: Clang keeps changing, …
=> P9 Float128 add/sub with round to odd, plus P8 equivalent.

src/pveclib/vec_f128_ppc.h, src/pveclib/vec_f32_ppc.h, src/pveclib/vec_f64_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/arith128_test_f32.c, src/testsuite/arith128_test_f64.c, src/testsuite/vec_f32_dummy.c, src/testsuite/vec_f64_dummy.c
Rebased after the add/subqpo merge. Cliose #158 
Seems the GCC (and Clang followed) initially reversed the operands
for vec_cpsgn() (so the sign is copied from operand b into a).
This differs from the Intrinsic reference and ISA that say the sign
is copied from operand a into b.
Unfortunately PVECLIB implementations of vec_copysignf32(),
vec_copysignf64(), and vec_copysignf128() duplicated the results of
original GCC vec_cpsgn() for the implementation,
This has been reported as a bug and now GCC and Clang are in the
process of "fixing" this bug to match the Intrinsic reference guide.
The fix will be applied to currently supported versions but older
compiler version will remain unchanged.
This change set will correct the PVECLIB copysign implementation
to match the intrinsic reference …
=> Fix vec_copysign implementations per issue #158, Part 1B.

src/pveclib/vec_f32_ppc.h, src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_print.c, src/testsuite/arith128_print.h, src/testsuite/arith128_test_i64.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
During work on vec_f128_ppc.h, to implement P9 operations
for P8, found anomalies with compiler generation for small
vector integer DW constants. Exponents are handled as DWs
for arithmetic and compares.
See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104124
The compiles wants to convert vec_spats(<small-DW-int>) into a
vector load on P8, while it is a 2 instruction immediate
sequence on P9 and could be also on P8. This happens even
for splat immediate words that are cast to DW.
The associate loads require more cycles and cause register
pressure and vector spill reload and associated load-hit-store
rejects.
* src/pveclib/vec_f32_ppc.h:
Include <pveclib/vec_int128_ppc.h>, avoids citcular dependency
between vec_int128_ppc.h and vec_int64_ppc.h.
* src/pveclib/vec_int64_ppc.h …
=> Fixes and work-arounds for int64.

src/pveclib/vec_f128_ppc.h, src/testsuite/pveclib_perf.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_perf_f128.c, src/testsuite/vec_perf_f128.h, src/testsuite/vec_pwr9_dummy.c
Still working around the compiler (GCC) that will generate extraneous
store/reloads. This seems to be related to loading vector constants
that have multiple uses and long live-ranges. Work-arounds include:
1) Using vec_splat_s64/vec_splat_u64 to avoid loads from .rodata.
2) Eliminate/consolidate constants that exceed the (-16 <-> 15)
immediate constant range,
3) Move constants to appropriate local scope.
4) Replace if/then/else blocks with boolean select logic.
5) Use __builtin_expect to optimize the common path (finite not
zero/denormal) to fall through code.
Still not clear what is going on (cause/effect) here. It should not
be registers pressure as analysis show that the code does not all
the volatile VRs (4 remain unused) and only 2 of the available
volatile VSRs.  I suspect the …
=> Performance tuning for mulqpo. Part2

src/pveclib/vec_int128_ppc.h, src/testsuite/arith128_test_i128.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_pwr9_dummy.c
New operations to avoid stoirage load and cache misses while using
small quadword integer constants. This became evident during the
implementation of float128 implementation.
* src/pveclib/vec_int128_ppc.h [int128_const_0_0_3]:
Doxygen subsection for Loading small Quadword constants.
(vec_splat_s128, vec_splat_u128): New int128 operations.
* src/testsuite/arith128_test_i128.c (test_splat_128):
New unit test.
(test_vec_i128): Add unit test to driver.
* src/testsuite/vec_int128_dummy.c (__test_splatisq_16,
__test_splatisq_n1, __test_splatisq_0, __test_splatisq_n1_V1,
__test_splatisq_n1_V0, __test_splatisq_0_V0,
__test_splatisq_signmask_V0, __test_splatisq_15_V2,
__test_splatisq_15_V1, __test_splatisq_15_V0,
__test_splatisq_15, __test_splatisq_127, __test_splatiuq_0,
__test_splatiuq_15, …
=> Operations for generating small quadword integer const values.

src/pveclib/vec_int64_ppc.h, src/testsuite/vec_int64_dummy.c
Document new operations to avoid stoirage load and cache misses while
using small doubleword integer constants. This became evident during
the implementation of float128 implementation.
* src/pveclib/vec_int64_ppc.h [i64_missing_ops_0_2_0]:
New doxygen subsection for Loading small Doubleword constants.
* src/testsuite/vec_int64_dummy.c (__test_splatudi_15_V1,
__test_splatudi_15_V0, __test_splatudi_10_V0,
__test_splatudi_1_V1, __test_splatudi_1_V0,
__test_splatudi_128_V1, __test_splatudi_128_V0,
__test_splatudi_smask_V0, __test_splatudi_n1_V1,
__test_splatudi_n1_V0, __test_incud_V0. __test_incuw_V0,
__test_incsd_V0): New compile teasts.
=> Operations for generating small doubleword integer const values.

src/pveclib/vec_f128_ppc.h, src/pveclib/vec_int128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/arith128_test_i128.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
Power9 provide round to odd versions for the QP arithmetic operations.
This patch provides an update P9/8 implementation for add/sub QP with
round to odd. This version includes optimization in constant loading
and logic simplification.
* src/pveclib/vec_f128_ppc.h [doxygen]: General updates.
[f128_softfloat_0_0_4]: New section
"Constants and Masks for Quad-Precision Soft-float".
[f128_softfloat_0_0_4_1]: New section
"Special Constants for Quad-Precision Soft-float".
[f128_softfloat_0_0_4_1_3]: New paragraph
"Some constants are trickier"
(union __VF_128): Add field ix1 scalar __int128.
[@cond INTERNAL]: Add forward ref for vec_xxxexpqpp.
(vec_const64_f128_128, vec_const128_f128_128,
vec_mask64_f128exp, vec_mask128_f128exp,
vec_mask128_f128mag, vec_mask128_f128sig,
vec_mask128_f128sign, …
=> Update Float128 add/sub with round to odd for P8. V2.

src/decpowof2.c, src/testsuite/arith128_test_i128.c
General cleanup.
* src/decpowof2.c: Add Apache License text to comments.
* src/testsuite/arith128_test_i128.c [test_addcq]: 
Correct vector type for variable l. 
[test_addeq]: Correct vector type for variable m. 
[test_vec_muludq]: Conditionally define level 2 debug. 
[test_muludq]: Correct vector type for variable l. 
[test_vec_madduq, test_vec_madd2uq]: 
Conditionally define level 2 debug. 
[test_madduq]: Correct vector type for variable l.
=> Cleanup for -Mall reported error and add missing License text.

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/pveclib_perf.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_perf_f128.c, src/testsuite/vec_perf_f128.h, src/testsuite/vec_pwr9_dummy.c, src/vec_runtime_DYN.c
Power9 provide round to odd versions for the QP arithmetic operations. This patch provides P9/8 implementation for multiply-add QP with round to odd. Includes compile, unit, and performance tests.
* src/pveclib/vec_f128_ppc.h [f128_softfloat_IRRN_0_1_3]: Update doxygen "IR for multiply" with diagrams. [f128_softfloat_IRRN_0_1_4]: New "IR for multiply add". [f128_softfloat_0_0_3_4]: New subsection "Multiply-Add Quad-Precision with Round-to-Odd". General doxygen improvements. (vec_xsmaddqpo): New inline operation. (vec_xsmulqpo): Clean up -Wall warnings for unused vars.
* src/testsuite/arith128_test_f128.c (db_vec_maddqpo): New debug function. (test_mask_f128): Add test for vec_const64_f128_112. (test_madd_qpo_xtra_c1, test_madd_qpo_xtra_c2, test_madd_qpo_xtra_c3, test_madd_qpo_xtra_c4, …
=> P9 Float128 Multiply-Add with round to odd, plus P8 equivalent.

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_pwr9_dummy.c
Power9 provides round to odd versions for the QP arithmetic operations. This patch provides P9/8 implementation for multiply-sub QP with round to odd. Includes compile, unit, and performance tests. Also a small bug (issue #175) common to madd/msub was found and is included in this update.
* src/pveclib/vec_f128_ppc.h [f128_softfloat_0_0_3_4_0]: 
Update doxygen code to match code changes. 
[f128_softfloat_0_0_3_5]: Add doxygen text for Multiply-Sub
Quad-Precision with Round-to-Odd. 
[__clang_major__]: Try to fix Clang 15/16.
(vec_xsmaddqpo): Small update to doxygen description. 
Update code to fix issue #175. (vec_xsmsubqpo): New PVECLIB operation.
* src/testsuite/arith128_test_f128.c (db_vec_maddqpo): 
Update code to fix issue #175. [test_xsmaddqpo]: 
Define operation for unit-test. …
=> P9 Float128 Multiply-Sub with round to odd, plus P8 equivalent.

src/Makefile.am, src/Makefile.in, src/pveclib/vec_common_ppc.h, src/pveclib/vec_f128_ppc.h, src/pveclib/vec_int128_ppc.h, src/pveclib/vec_int512_ppc.h, src/testsuite/arith128_test_qpo.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_perf_f128.c, src/vec_f128_runtime.c, src/vec_runtime_DYN.c, src/vec_runtime_PWR10.c, src/vec_runtime_PWR7.c, src/vec_runtime_PWR8.c, src/vec_runtime_PWR9.c
The Float128 arithmetic operations xs[add|sub|mul|madd|msub|...] are generally too large for in-lining. So rename the static inline operations with the "_inline" suffix. Then create
src/vec_f128_runtime.c to provide static implementations using the static inline operations from vec_f128_ppc.h for each operation. The vec_f128_runtime.c file is #included in
src/vec_runtime_PWR[7|8|9|10].c files to build the build the libpvecstatic archive. Finally update src/vec_runtime_DYN.c to define the resolvers and IFUNC aliases for each operation. With library rebuilt we can update the unit/performance tests to call the library implementations.
* src/Makefile.am (vec_dynrt_PWR10.lo, vec_dynrt_PWR9.lo vec_dynrt_PWR8.lo, vec_dynrt_PWR7.lo): Add depenency on vec_f128_runtime.c. (vec_staticrt_PWR10.lo, …
=> Add QP round-to-odd operations to runtime library. Close #178.

src/pveclib/vec_char_ppc.h, src/pveclib/vec_f128_ppc.h, src/pveclib/vec_int128_ppc.h, src/pveclib/vec_int16_ppc.h, src/pveclib/vec_int32_ppc.h, src/pveclib/vec_int512_ppc.h, src/testsuite/arith128_test_bcd.c
The initial P10 code used inline asm as the GCC intrinsic support was not complete. With the latest compilers vector intrinsic are (mostly) complete. It is better to use the vector instinsics when available.
* src/pveclib/vec_char_ppc.h (vec_absdub): Use vec_absdb intrinsic, if defined. (vec_setb_sb [__GNUC__ >= 12]): Use vec_expandm intrinsic for GCC 12 and later.
* src/pveclib/vec_f128_ppc.h (vec_xscvuqqp, vec_xsmaddqpo, vec_xsmaddqpo_inline, vec_xsmsubqpo): Update doxygen comments.
* src/pveclib/vec_int128_ppc.h (vec_msumcud [__GNUC__ >= 12]): Use vec_msumc intrinsic for GCC 12 and later. (vec_msumudm [__GNUC__ >= 12]): Use vec_msum intrinsic for GCC 12 and later. (vec_mulhud [__GNUC__ >= 12]): Use vec_mulh intrinsic for GCC 12 and later. (vec_muloud): Update doxygen comments. …
=> Update for POWER10 Intrinsic support.

src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_test_i64.c, src/testsuite/pveclib_perf.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_perf_i128.c, src/testsuite/vec_perf_i128.h, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
POWER10 added vector divde/divide-extended/modulo instrictions. This is the initial patch for the doubleword implementations. A later patch will add the platform specific implementations for static and IFUNC enabled dynamic libraries.
* src/pveclib/vec_int64_ppc.h: General updates. [i64_missing_ops_0_0_PWR8]: New subsection "POWER8" header. [i64_missing_ops_0_0_PWR9]: New subsection "POWER9" header. [i64_missing_ops_0_0_PWR10: New subsection "POWER10" header. [i64_missing_ops_0_1]: New subsection test "Challenges and opportunities". [i64_missing_ops_0_2_1]: Update subsubsection "Doubleword integer multiplies". General updates. [i64_missing_ops_0_2_2]: New subsubsection text "Doubleword Integer Divide/Modulo". [i64_missing_ops_0_2_2_0]: New paragraph text "Vectorizable Divide …
=> Add P10 divide/modulo operations for doubleword.

doc/pveclib-doxygen-pveclib.doxy, doc/pveclibmaindox.h, src/pveclib/vec_int128_ppc.h, src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_test_i128.c, src/testsuite/arith128_test_i512.c, src/testsuite/pveclib_perf.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_perf_i128.c, src/testsuite/vec_perf_i128.h, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
POWER10 added vector divde/divide-extended/modulo instructions. This is the initial patch for the quadword implementations. Also some general Wall fixups and latent compile error fixes. A later patch will add the platform specific implementations for static and IFUNC enabled dynamic libraries.
* doc/pveclib-doxygen-pveclib.doxy [FORMULA_TRANSPARENT, LATEX_SOURCE_CODE, CLASS_DIAGRAMS, DOT_FONTNAME, DOT_FONTSIZE, DOT_TRANSPARENT]: Remove tags that are no longer support is recent doxygen versions.
* doc/pveclibmaindox.h: Escape \# for pragma to fix formating.
* src/pveclib/vec_int128_ppc.h: Update copyright year. General doxygen text updates, mostly POWER10 related. [int128_multiply_0_1]: New Subsection Implementing Quadword Multiply. [int128_multiply_0_1_0_0]: New subsubsection POWER7/8 …
=> Add P10 divide/modulo operations for quadword.

src/Makefile.am, src/Makefile.in, src/pveclib/vec_int128_ppc.h, src/testsuite/arith128_test_i128.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_perf_i128.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c, src/vec_int128_runtime.c, src/vec_runtime_DYN.c, src/vec_runtime_PWR10.c, src/vec_runtime_PWR7.c, src/vec_runtime_PWR8.c, src/vec_runtime_PWR9.c
POWER10 added vector divide/divide-extended/modulo instructions. This patch adds static and IFUNC enabled dynamic callable functions to the PVECLIB executable library. This is restricted to the subset of operations that have significant code size or runtime. This is basically the divide/modulo operations; vec_divduq, vec_diveuq, vec_divdqu, vec_divuq, vec_modduq, vec_moduq.
* src/Makefile.am: Add vec_int128_runtime.c to dependency for PWR library builds. Add Automake regenerated.
* src/Makefile.in: Automake regenerated.
* src/pveclib/vec_int128_ppc.h: Update copyright dates. Various doxygen text updates for POWER10. Includes correcting the spelling of vec_diveuq many times. Also renamed __VEC_U_128P to the more descriptive __VEC_U_128RQ. [__VEC_U_128RQ]: Renamed from __VEC_U_128P. …
=> Add P7/8/9/10 divide/modulo quadword operations to libraries.

src/pveclib/vec_char_ppc.h
The documentation comments for the two functions were swapped. It seems that the latency measurements were correct, though, as the more complex isalnum documents a longer latency, so these were kept as is.
=> Fix swapped docstrings of isalpha and isalnum

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/arith128_test_i128.c, src/testsuite/arith128_test_qpo.c, src/testsuite/arith128_test_qpo.h, src/testsuite/pveclib_perf.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_perf_f128.c, src/testsuite/vec_perf_f128.h, src/testsuite/vec_pwr10_dummy.c, src/vec_f128_runtime.c, src/vec_runtime_DYN.c
This patch provides P9/8 implementation for Divide QP with round to odd. Includes compile, unit, and performance tests.
* src/pveclib/vec_f128_ppc.h: Update into documentation for soft-float implementation. [f128_softfloat_0_0_3_6]: New subsubsection for Divide QP. [f128_softfloat_0_0_3_6_0, f128_softfloat_0_0_3_6_1, f128_softfloat_0_0_3_6_2]: New paragraph for; Soft-float divide QP, Special value handling, and custom divide extended. (vec_diveuqo_inline): New inline implementation. (vec_xsdivqpo): New dynamic call IFUNC implementation. (vec_xsdivqpo_inline): New inline implementation.
* src/vec_f128_runtime.c (vec_xsdivqpo): New runtime implementation.
* src/vec_runtime_DYN.c (vec_xsdivqpo): New CPU impementation externs and resolver.
* src/testsuite/arith128_test_f128.c (test_div_qpo, …
=> Power9 provides round to odd versions for the QP arithmetic operations.

src/pveclib/vec_char_ppc.h, src/testsuite/arith128_test_char.c, src/testsuite/vec_char_dummy.c, src/testsuite/vec_pwr9_dummy.c
This updates includes operations for;
Vector Count Leading Zero Least-Significant Bits Byte, Vector Count Trailing Zero Least-Significant Bits Byte, Vector Compare Not Equal or Zero Byte.
enabled for POWER7/8/9.
Operations listed as Power Bi-Endian enabled per the Power Vector Intrinsic Programming Reference are supported.
Includes additional compile and unit tests.
* src/pveclib/vec_char_ppc.h: Update Doxygen intro. (vec_vclzlsbb, vec_vctzlsbb): function prototype. (vec_cntlz_lsbb_bi, vec_cnttz_lsbb_bi): New inline Bi-Endian function. (vec_vclzlsbb, vec_vctzlsbb, vec_vcmpnezb): New inline functions.
* src/testsuite/arith128_test_char.c (db_vec_clzlsbb): New debug function. (test_vec_cmpnezb, test_vec_clzlsbb, test_vec_ctzlsbb): New unit-tests. (test_vec_cntlz_lsbb, test_vec_cnttz_lsbb): …
=> This patch provides new char/byte operations introduced in P9.

src/pveclib/vec_char_ppc.h, src/testsuite/arith128_test_char.c, src/testsuite/vec_char_dummy.c
Failing compiler tests for;
- Vector Count Leading Zero Least-Significant Bits Byte,
- Vector Count Trailing Zero Least-Significant Bits Byte,
- Vector Compare Not Equal or Zero Byte.
The Power vector intrinsic reference specifies type generic vec_cmpne and vec_popcnt.
Older compilers may not implement vec_cmpne but do implement vec_cmpeq which can be combined with vec_not/vec_nor or vec_andc/vec_orc to get the some effect.
Older GCC compilers supporting power8 will provide vec_vpopcntb/vec_vpopcnth but may not provide the generic vec_popcnt for byte/halfword. Newer GCC compilers still support vec_vpopcntb/vec_vpopcnth and the generic vec_popcnt. Clang compilers that support power8 and vpopcntb/h instructions only support the generic vec_popcnt.
PVECLIB's vec_char_ppc.h implementations …
=> This updates char/byte operations introduced in P9. Fix #194

src/pveclib/vec_int128_ppc.h, src/testsuite/arith128_test_i128.c, src/testsuite/vec_int128_dummy.c
The Power8/9 implementation of divide extended quadword (vec_vdiveuq_inline() and special round to odd version (vec_diveuq_qpo()) used in float128 vec_xsdivqpo_inline) is sub-optimal. For power8/9 the implementation is a long division by doublewords using vec_divqud_inline(). This is a 128 by 64-bit divide returning a 64-bit quotient and remainder. Effectively a 4-digit dividend by 2 digit division in two steps where each digit is 64-bits.
In the extended divide case, and the divisor has two nonzero (doubleword) digits, an explicit multiple/subtract is required to obtain the remainder. Initially the implementation used a quadword by quadword multiply (vec_muludq ()). This is not required as a quadword by double word multiply is sufficient if you are carefull with the subtraction (a double …
=> Update-p2 P10 divide operations for quadword. Closing #196

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_qpo.c, src/testsuite/vec_f128_dummy.c
The Power8/9 implementation of divide extended quadword (vec_vdiveuq_inline() was improved. This was the basis for the special round to odd version (vec_diveuq_qpo()) used in float128 vec_xsdivqpo_inline()) This is sub-optimal for this case.
In the extended divide case, and the divisor has two nonzero (doubleword) digits, an explicit multiple/subtract is required to obtain the remainder. The optimized implementation needs a (128 by 64-bit) multiply that is not defined within vec-int128_ppc.h but can be constructed using vec_vmuloud() and vec_vmaddeud(). The vec_diveuq_qpo() implementation uses this method and also checks the final remainer for nonzero. A nonzero remainder causes the LSB 1 to be ORed into the quotient (Round-to-Odd).
* src/pveclib/vec_f128_ppc.h[f128_softfloat_0_0_3_6_0]: …
=> Update-p2 Float128 divide round to odd improvement. Close #196

src/pveclib/vec_char_ppc.h, src/testsuite/arith128_test_char.c, src/testsuite/vec_char_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
The Power vector intrinsic reference specifies type generic instrinsics for ISA 3.0:
- vec_cmpne
- vec_first_match_index
- vec_first_match_or_eos_index
- vec_first_mismatch_index
- vec_first_mismatch_or_eos_index
and ISA 3.1
- vec_test_lsbb_all_ones
- vec_test_lsbb_all_zeros
PVECLIB supports type specific implementations (of the above) for P7/8/9/10 and fills in gaps in the compiler support:
- vec_vcmpneb
- vec_first_match_byte_index
- vec_first_match_byte_or_eos_index
- vec_first_mismatch_byte_index
- vec_first_mismatch_byte_or_eos_index
- vec_testlsbb_all_ones
- vec_testlsbb_all_zeros
The operation names above are chosen to avoid name conflicts with altivec.h.
* src/pveclib/vec_char_ppc.h (vec_vcmpneb, vec_vcmpnezb [@cond INTERNAL]): Add forward prototypes. (vec_first_match_byte_index, …
=> Add char/byte operations introduced in P9/10. Part 3

src/pveclib/vec_f128_ppc.h, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_pwr9_dummy.c
The float128 implementations need various vector masks and integer constants. These can be loaded as initialized vector constants from storage (.rotate section). But this comes a cost (see "Loading constants for masking Float128 fields" in the vec-f128_ppc.h docs).
For many cases it is better to use short splat-immediate/shift/rotate sequences to generate these constants. The mask generator code is already on master, but I noticed the some older operations that can take advantage of these generators. This is one stage of the required cleanup.
* src/pveclib/vec_f128_ppc.h [f128_softfloat_0_0_0_1]: New doxygen subsubsection for "Loading constants for masking Float128 fields". [f128_softfloat_0_0_0_2]: New doxygen subsubsection for "Alternative mask generation". (vec_mask128_f128sign): …
=> Cleanup and optimizations for Float128. Part 1

src/pveclib/vec_char_ppc.h, src/pveclib/vec_common_ppc.h, src/pveclib/vec_f64_ppc.h, src/pveclib/vec_int128_ppc.h, src/pveclib/vec_int32_ppc.h, src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_test_char.c, src/testsuite/arith128_test_i128.c, src/testsuite/arith128_test_i16.c, src/testsuite/arith128_test_i32.c, src/testsuite/arith128_test_i64.c, src/testsuite/vec_char_dummy.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_int16_dummy.c, src/testsuite/vec_int32_dummy.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
Set out to implement the POWER10 string operations Vector Clear Leftmost/Rightmost Bytes, Vector String Isolate Byte Left/Right-justified, and Vector String Isolate Byte (Predicate) operations. Quickly discovered P9/8/7 implementation requires the equivalent of clz/ctz quadword with circular dependencies on vec_int128_ppc.h
Decided the only way out was to drag some of the implementation (and associated dependencies) down to vec_common_ppc.h. The effort grew in size to avoid dependencies on vec_int64_ppc.h and vec_int32_ppc.h. Without access to those implementation needed new implementations with dependencies only on vec_common_ppc.h, and altivec.h. This is the result of that work.
This caused some rethinking of implementation. This lead to some cleanup and simplification of the of …
=> Add char/byte operations introduced in P9/10. Part 4 close #201

src/pveclib/vec_common_ppc.h
Closes #204 
A common thread through quadword multiply/divide/float128 implementations comes down to small Double/Quadword constants and especially shift counts for Double/Quadword shift/rotate operations. GCC changes introduced with LE changes (GCC 8+) made this all harder and less efficient (See GCC PRs 117007, 117718, 117818). This patch provides the core implementation (as a work-around) to generate 6-7 bit immediate shift-counts while avoiding loads from .rodata. It also provides pveclib shift/rotate double/quadword operations that accept vector unsigned char as the shift count. This prevents GCC constant-propagation from converting pveclib 6/7-bit splat immediate operations into .rodata constants.
Further changes are required up the operation stack (int32/64/128 and f32/64/128) to …
=> Add common parts for shift/rotate immediate GCC bugs. Issue #204.

src/pveclib/vec_char_ppc.h, src/pveclib/vec_common_ppc.h, src/testsuite/arith128_test_char.c, src/testsuite/vec_char_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
* src/pveclib/vec_char_ppc.h (vec_ctzb[_ARCH_PWR8]): Use tzmask and popcntb for implementation.
- (vec_expandm_byte): New inline operation.
- (vec_first_mismatch_byte_or_eos_index[_ARCH_PWR9]): And (__VSX__) and (__GNUC__ > 7)
- (vec_rlbi): New inline operation.
- (vec_slbi): Update P10 latency. Eliminate unnecessary cast.
- (vec_srabi): Update P10 latency. Rename var lshift to rshift.
- (vec_srbi): Update P10 latency. Rename var lshift to rshift.
* src/testsuite/arith128_test_char.c (test_splat6_u8, test_splat6_s8, test_splat7_u8, test_expandm_byte): New unit tests.
- (test_vec_char): Add new unit tests to driver.
* src/testsuite/vec_char_dummy.c
- (test_vec_expandm_byte): New compile test.
- (test_splat7_u8_15, test_splat7_u8_16, test_splat7_u8_18, test_splat7_u8_27, test_splat7_u8_30, …
=> Add exploit common parts for char/byte and P10.

src/pveclib/vec_int16_ppc.h, src/testsuite/arith128_test_i16.c, src/testsuite/vec_int16_dummy.c
* src/pveclib/vec_int16_ppc.h (vec_expandm_halfword): New inline operation.
- (vec_popcnth[!_ARCH_PWR7]): Leverage vec_common_ppch vec_popcnth_PWR7 implementation.
- (vec_rlhi): New inline operation.
- (vec_signexts_byte, vec_vextsb2h): New inline operation.
- (vec_slhi): Doxygen add P10 latency. Remove unnecessary cast.
- (vec_srhi): Doxygen add P10 latency. Rename lshift to rshift.
- (vec_srahi): Doxygen add P10 latency. Rename lshift to rshift.
* src/testsuite/arith128_test_i16.c (test_expandm_halfword, test_signexts_b): New unit tests.
- (test_vec_i16): Update driver to call new unit tests.
* src/testsuite/vec_int16_dummy.c
- (test_vec_vextsb2h, test_vec_signexts_byte, test_signexts_byte_V1, test_signexts_byte_V0, test_vec_expandm_halfword): New compile tests.
- (test_vec_rlhi_4, …
=> Add exploit common parts for short/halfword and P10.

src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_test_i64.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
* src/pveclib/vec_int64_ppc.h (vec_sradi): Forward declare prototype.
- (vec_addudm, vec_clzd, vec_ctzd):  Update latency.
- (vec_expandm_doubleword): New inline operation.
- (vec_popcntd): Update latency.
- (vec_setb_sd): Update latency. Use vec_expandm_doubleword for implementation.
- (vec_rldi): Update latency. Replace implementation with vec_rldi_PWR8 (vra, (shb%64)).
- (vec_sldi): Update latency. Replace implementation with vec_vsld_PWR8 (vra, vec_splat6_u8 (shb)).
- (vec_signextll_byte, vec_signextll_halfword, vec_signextll_word): New inline operations.
- (vec_srdi): Update latency. Replace implementation with vec_vsrd_PWR8 (vra, vec_splat6_u8 (shb).
- (vec_sradi): Update latency. Replace implementation with vec_vsrad_PWR8 (vra, vec_splat6_u8 (shb)) and vec_vexpanddm_PWR10.
- …
=> Add exploit common parts for long long /doubleword and P10.

src/pveclib/vec_common_ppc.h, src/pveclib/vec_int32_ppc.h, src/testsuite/arith128_test_i32.c, src/testsuite/vec_int32_dummy.c
* src/pveclib/vec_int32_ppc.h (vec_slwi, vec_vrlw_byte, vec_vslw_byte, vec_vsraw_byte, vec_vsrw_byte): Forward declare prototype.
- (vec_clzw, vec_ctzw): Update latency.
- (vec_expandm_word): New inline operation.
- (vec_mrgew[_ARCH_PWR7]): Add P7 specific implementation and associated latency.
- (vec_mrgow[_ARCH_PWR7]): Add P7 specific implementation and associated latency.
- (vec_popcntw): Update latency.
- (vec_setb_sw): Update latency. Use vec_expandm_word() for implementation.
- (vec_signexti_byte, vec_signexti_halfword): New inline operations.
- (vec_vextsb2w, vec_vextsh2w): New inline operations.
- (vec_rlwi): New inline operation.
- (vec_slwi): Update latency. Replace implementation with vec_vslw_byte (vra, vec_splat5_u8 (shb)).
- (vec_srawi): Update latency. Replace …
=> Add exploit common parts for int/word and P10.

src/pveclib/vec_int128_ppc.h, src/pveclib/vec_int64_ppc.h, src/testsuite/arith128_test_i128.c, src/testsuite/vec_int128_dummy.c, src/testsuite/vec_int64_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c
* src/pveclib/vec_int128_ppc.h
- (vec_vsldbi, vec_vslq_byte, vec_vsraq_byte, vec_vsrq_byte): Remove, deprecate forward declares.
- (vec_expandm_quadword): New inline operation.
- (vec_rlq): Update doxygen text. Use vec_vrlq_PWR10/vec_vrlq_PWR9 from vec_common_ppc.h.
- (vec_rlqi): Update doxygen text. Use vec_rlqi_PWR10 from vec_common_ppc.h.
- (vec_setb_sq): Update doxygen text. Use vec_expandm_quadword.
- (vec_signextq_doubleword, vec_signextq_byte, vec_signextq_halfword, vec_signextq_word): New inline operations.
- (vec_vextsd2q, vec_vextsb2q, vec_vextsh2q, vec_vextsw2q): New inline operations.
- (vec_sldb_quadword): New inline operation.
- (vec_sldqi): Update doxygen text. Use vec_sldbi_PWR10 from vec_common_ppc.h.
- (vec_slq): Update doxygen text. Simplify types. Use …
=> Add exploit common parts for __int128 and P10.

src/pveclib/vec_f64_ppc.h, src/testsuite/vec_f64_dummy.c
generating vector DW integer constants for DP float masks are difficult for _ARCH_PWR7/8 and not so easy for _ARCH_PWR9. Fortunately _ARCH_PWR9 includes DP exponent/signifcand extract/inserts and vec_test_data_class operations.
But that leaves some coding work for _ARCH_PWR7/8 which requires DW shift, range compare, and mask generation. Unfortunately the compiler generate sub-optimal code for vector const (.rodata) loads for _ARCH_PWR7/8/9. So where possible should use splat-immediate, shift, rotate, and logical operations and avoid vector constant loads (see issue #204).
So this update uses the vec_common_ppc.h support for DW shift/rotate and splat immediate beyond the range (-16 to 15). The header vec_f64_ppc.h now includes a number of helper operations to generate DP float mask and …
=> Add exploit common parts for f64 and P10.

src/pveclib/vec_f32_ppc.h, src/testsuite/vec_f32_dummy.c
Exploit the vec_common_ppc.h work on generating constants and shift immediates. This eliminates loads from ./rodata and related problems described in issue #204.
* src/pveclib/vec_f32_ppc.h (vec_mask32_f32sign, vec_mask32_f32mag, vec_mask32_f32sig, vec_mask32_f32exp, vec_mask32_f32hidden): New inline operations to generate integer masks and exponents.
- (vec_absf32, vec_all_isfinitef32): Update doxygen latency table.
- (vec_all_isfinitef32): Use vec_mask32_f32exp constant.
- (vec_all_isinff32): Update doxygen latency table. Use vec_mask32_f32exp and vec_mask32_f32sign constants.
- (vec_all_isnanf32): Update doxygen latency table. Use vec_mask32_f32exp and vec_mask32_f32sign constants.
- (vec_all_isnormalf32): Update doxygen latency table. Use vec_mask32_f32exp constant.
- …
=> Add exploit common parts for f32 and P10.

src/pveclib/vec_f128_ppc.h, src/testsuite/arith128_test_f128.c, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_pwr10_dummy.c, src/testsuite/vec_pwr9_dummy.c, src/vec_f128_runtime.c, src/vec_runtime_DYN.c
Complete exploitation of common splat and shift immediate support. Also complete the migration of large f128 implementations to librarys with IFUNC resolvers
* src/pveclib/vec_f128_ppc.h (vec_mask128_f128mag, vec_mask128_f128Lbit): Forward prototypes.
- (vec_const64_f128_63, vec_const64_f128_112, vec_const64_f128_116, vec_const64_f128_127, vec_const64_f128bias, vec_const64_f128maxe, vec_const64_f128naninf, vec_const128_f128_fmax, vec_mask64_f128exp, vec_mask128_f128Xbits): New helper operations.
- (vec_all_isfinitef128, vec_all_isnormalf128): use vec_mask128_f128exp.
- (vec_all_issubnormalf128): Use vec_splat_u32, vec_mask128_f128Lbit, and vec_mask128_f128sign.
- (vec_all_iszerof128): Use vec_splat_u32 and vec_mask128_f128sign. Improve code.
- (vec_const_huge_valf128): Use …
=> Add exploit common parts for float128 and P10 plus IFUNC.

src/pveclib/vec_f128_ppc.h, src/testsuite/vec_f128_dummy.c, src/testsuite/vec_pwr9_dummy.c
The xfer and mask operations between __float128 and vector int using unions exposed poor optimizations starting with GCC 8 and continuing through GCC 11. For the POWER7/8 target GCC would generate vector store then reload sequences for what should be a simple vector register transfer. This had devastating impacts on performance.
This appears to be fixed for GCC 12 and 13 and I assume 14/15. So this update changes the macros logic to reenable the union transfers for those versions of __GNUC__.
* src/pveclib/vec_f128_ppc.h (vec_sel_bin128_2_bin128, vec_and_bin128_2_vui32t, vec_andc_bin128_2_vui32t, vec_or_bin128_2_vui32t, vec_xor_bin128_2_vui32t, vec_andc_bin128_2_vui128t, vec_xfer_bin128_2_vui8t, vec_xfer_bin128_2_vui32t, vec_mrgh_bin128_2_vui64t, vec_mrgl_bin128_2_vui64t, …
=> Continue updates to vec_float128, add compiler optimizations.
